import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';


export default function Footer() {
    return(
        <div>
            <Head>
            <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
        <link href="/style/plugins/plugins.min.css/" rel="stylesheet"></link>
        <link href="/style/vendor/vendor.min.css/" rel="stylesheet"></link>
        <link rel="icon" href="/logo (1).png" />
            </Head>

            <div className="footer-area">
        <div className="footer-container">
          <div className="footer-top">
            <div className="container">
              <div className="row">
                <div
                  className="col-md-6 col-lg-4 mb-md-30px mb-lm-30px"
                  data-aos="fade-up"
                  data-aos-delay="200"
                >
                  <div className="single-wedge ">
                    <Image
                      width={128}
                      height={128}
                      className=""
                      src="/assets/images/logo/logo.png"
                      alt=""
                    />
                    <p className=" my-2 sahil">
                      <i
                        className="fa fa-arrow-circle-right "
                        aria-hidden="true"
                      ></i>
                      Unit 8A Stag Industrial Estate,
                    </p>
                    <p>Oxford Street, Bilston,</p>
                    <p>WV14 &nbsp;7HZ,</p>
                    <p>01902 &nbsp;405535,</p>
                    <p>
                      <i className="fa fa-envelope-o" aria-hidden="true"></i>
                      &nbsp;&nbsp;info@bedsdivans.co.uk
                    </p>
                    <p className="my-5">
                      <Image
                        width={128}
                        height={128}
                        src="/assets/images/logo/yell.jpg"
                        alt=""
                      />
                      &nbsp;Trusted by Yell
                    </p>
                    {/* <p className="footer-herading my-2"><i className="fa fa-arrow-circle-right" aria-hidden="true"></i>Unit 8A Stag Industrial Estate</p> */}
                  </div>
                </div>

                <div
                  className="col-md-6 col-sm-6 col-lg-3 mb-md-30px mb-lm-30px footer2-margin"
                  data-aos="fade-up"
                  data-aos-delay="400"
                >
                  <div className="single-wedge">
                    <h4 className="footer-herading">USEFUL LINKS</h4>
                    <div className="footer-links">
                      <div className="footer-row">
                        <ul className="align-items-center">
                          <li className="li">
                            <a className="single-link" href="about.html">
                              Diven Beds
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="#">
                              Suede Divan Bed
                            </a>
                          </li>
                          <li className="li">
                            <a
                              className="single-link"
                              href="privacy-policy.html"
                            >
                              Headboards
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="#">
                              Mattressess
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="#">
                              Velvet Fabric Diven Beds
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="#">
                              Sleigh Beds
                            </a>
                          </li>
                        </ul>
                        <hr className="my-4" />
                        <ul className="align-items-center">
                          <h4 className="footer-herading my-6">BLOGS</h4>
                          <li className="li">
                            <a className="single-link" href="about.html">
                              A Buying Guide To Distinct Sized Mattress
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                <div
                  className="col-md-6 col-lg-2 col-sm-6 mb-lm-30px"
                  data-aos="fade-up"
                  data-aos-delay="600"
                >
                  <div className="single-wedge">
                    <h4 className="footer-herading">Additional links</h4>
                    <div className="footer-links">
                      <div className="footer-row">
                        <ul className="align-items-center">
                          <li className="li">
                            <a href="/about" className="single-link">
                              About Us
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="/product/shop">
                              Shop
                            </a>
                          </li>
                          <li className="li">
                            <a href="/contact" className="single-link">
                              Contact Us
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="/ReturnPolicy">
                              Return Policy
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="/PrivacyPolicy">
                              Privacy Policy
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="checkout.html">
                              Diven Bed Yorkshire
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="checkout.html">
                              Diven Bed Birmingham
                            </a>
                          </li>
                          <li className="li">
                            <a className="single-link" href="checkout.html">
                              Diven Bed London
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                <div
                  className="col-md-6 col-lg-3 footer-margin"
                  data-aos="fade-up"
                  data-aos-delay="800"
                >
                  <div className="single-wedge">
                    <h4 className="footer-herading">top selected</h4>
                    <div className="footer-links">
                      <div id="mc_embed_signup" className="footer-4">
                        <p>
                          Mink Chenillie Divan Base or <br></br>
                          Set+Headboard+1500 Pocket Mattress<br></br>FREE HOME
                          DILIVERY
                        </p>
                        <p>White Velvet Cube Headboard</p>
                        <p>
                          White Crushed Velvet Divan Bed Set <br></br>
                          +Headboard+Mattress FREE UK DILIVERY
                        </p>
                        <p>
                          Gun Grey Crushed Velvet Divan Set <br></br>
                          +Headboard+1500 Pocket Pillow Top <br></br>Mattress
                          FREE UK DILIVERY
                        </p>
                        <p>
                          Orthopedic Foam and Spring Mattress <br></br>Medium
                          Frimness
                        </p>
                        <hr className="my-4" />
                        <ul className="text-center">
                          <a href="">
                            
                            <li>
                              <p>
                                <i
                                  className="fa fa-facebook"
                                  aria-hidden="true"
                                ></i>
                                <span>
                                  <i
                                    className="fa fa-facebook"
                                    aria-hidden="true"
                                  ></i>
                                </span>
                                <span>
                                  <i
                                    className="fa fa-facebook"
                                    aria-hidden="true"
                                  ></i>
                                </span>
                              </p>
                            </li>
                          </a>
                        </ul>

                        {/* <form id="mc-embedded-subscribe-form" className="validate" novalidate="" target="_blank" name="mc-embedded-subscribe-form" method="post" action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef">
                                            <div id="mc_embed_signup_scroll" className="mc-form">
                                                <input className="email" type="email" required="" placeholder="Your Mail*" name="EMAIL" value="" />
                                                <div className="mc-news" aria-hidden="true">
                                                    <input type="text" value="" tabindex="-1" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" />
                                                </div>
                                                <div className="clear">
                                                    <button id="mc-embedded-subscribe" className="button btn-primary" type="submit" name="subscribe" value=""><i
                                                            className="icon-cursor"></i> Send Mail</button>
                                                </div>
                                            </div>
                                        </form>  */}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <hr />
          <div className="container">
            <div className="row">
              <div className="col-md-6 text-left">
                <p className="copy-text">
                  <strong>Bedsdiven</strong> © 2021
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
        </div>
    )
}