import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import Link from "next/link";
import Menu from "./comps/Menu";
import { useRouter } from "next/router";
import ShoppingCartIcon from "@material-ui/icons/ShoppingCart";
import { useSelector } from "react-redux";
import axios from "axios";
import Box from '@mui/material/Box';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select from '@mui/material/Select';
export default function Header() {
  const [category, setAge] = React.useState('');

  const handleChange = (event) => {
    setAge(event.target.value);
  };
  const router = useRouter();
  const cart = useSelector((state) => state.cart);

  const [query, setQuery] = useState("");

  const { cartItems } = cart;

  const [autocomplete, setAutocomplete] = useState([]);

  //SEARCH BOX AUTOCOMPLETE

  useEffect(() => {
    if (!/^\s*$/.test(query)) {
      axios.get(`/api/autocomplete?search=${query}`).then((response) => {
        setAutocomplete(response.data);
      });
    }
  }, [query]);

  const getCartCount = () => {
    return cartItems.reduce((qty, item) => qty + item.qty, 0);
  };

  const handleSearch = (e) => {
    e.preventDefault();
    if (query) {
      router.push(`/product/shop?search=${query}`);
    }
  };

  const handleRoute = (category, title) => {
    console.log(category);
    switch (category) {
      case "bed":
        router.push(`/newproduct?title=${title}`);
        break;
      case "headboard":
        router.push(`/headboard/Headboardproduct?title=${title}`);
        break;
      case "mattress":
        router.push(`/mattressess/Mattressessproduct?title=${title}`);
        break;
    }
  };
  return (
    <div>
      <Head>
        {/* <tittle>BedsDivans</tittle> */}
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
        <link href="/style/plugins/plugins.min.css/" rel="stylesheet"></link>
        <link href="/style/vendor/vendor.min.css/" rel="stylesheet"></link>
        <link rel="icon" href="/logo (1).png" />
      </Head>

      <div className="header section">
        <div className="classic-header">
          <div className="header-top section-fluid   ">
            <div className="container">
              <div className="row row-cols-lg-2 align-items-center">
                <div className="col text-lg-left">
                  <div className="header-top-massege">
                    <p>Free Delivery over £40 to most of UK*</p>
                  </div>
                </div>

                <div className="col d-none d-lg-block">
                  <div className="header-top-set-lan-curr d-flex justify-content-end">
                    {/* <div className="header-top-content facebook-icon">
                      <Image src="/assets/images/icons/facebook.png" width={100} height={100} />

                    </div>
                    <div className="header-top-content facebook-icon">
                      <Image src="/assets/images/icons/facebook.png" width={100} height={100} />

                    </div> */}
                    <div className="header-top-content for-border">
                      <a href="/contact">
                        <button> Contact Us </button>
                      </a>
                    </div>

                    <div className="header-top-content">
                      <a href="/about">
                        <button>About us</button>
                      </a>
                    </div>
                    <div className="header-top-content">
                      <button>01902405535</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="header-bottom d-none d-lg-block">
          <div className="container position-relative Ncs ">
            <div className="row  ">
              <div className="col-md-2 align-self-center">
                <div className="header-logo">
                  <Link href="/home">
                    <Image
                      alt="BedsDivan"
                      src="/assets/images/logo/logo.png"
                      width={100}
                      height={100}
                    />
                  </Link>
                </div>
              </div>
              {/* New search start */}
              
              
{/* New search end */}
<div className="col-7 align-self-center" style={{marginTop:"10px"}}>
<div class="input-group ">
  <input type="text" class="form-control col-8" onChange={(e) => setQuery(e.target.value)}  placeholder="Search for product"/>
  <ul
                      className="search_suggestions"
                      style={{ display: query ? "block" : "none" }}
                    >
                      {autocomplete.length ? (
                        autocomplete.map((suggestion) => (
                          <li
                          
                            key={suggestion._id}
                            onClick={() =>
                              handleRoute(
                                suggestion.type,
                                suggestion.product_name
                              )
                            }
                          >
                            {suggestion.product_name}
                            <span>in {suggestion.type}</span>
                          </li>
                        ))
                      ) : (
                        <p style={{ textAlign: "center" }}>
                          Oops, No Result Found
                        </p>
                      )}
                      <li
                        style={{
                          textAlign: "center",
                          color: "grey",
                          padding: 5,
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontSize: 12,
                        }}
                        onClick={() =>
                          handleRoute(
                            suggestion.category,
                            suggestion.product_name
                          )
                        }
                      >
                        view all results{" "}
                      </li>
                    </ul>
  <div class="input-group-append col-4 p-0">
  <select class="form-control category-dropdown" id="sel1">
    <option>Divan Bed</option>
    <option>All Bed</option>
    <option>Headboard</option>
    <option>Mattress</option>
    <option>Sofa</option>
    <option>Garden Furniture</option>
    <option>Living room furniture</option>
    <option>Dining set</option>
  </select>
    <button
                        className="btn btn-danger search-btn"
                        type="submit"
                        onClick={handleSearch}
                      >
                        <img
                          src="/assets/images/image/Icon material-search.png"
                          style={{ height: "22px", opacity: "0.9" }}
                          alt="bedsdivans"
                        />
                      </button>
  </div>
</div>

</div>




{/* <div className="col-md-4 align-self-center">
<input
                        className="form-control"
                        placeholder="Search"
                        type="text"
                        onChange={(e) => setQuery(e.target.value)}
                      /> 
                      <ul
                      className="search_suggestions"
                      style={{ display: query ? "block" : "none" }}
                    >
                      {autocomplete.length ? (
                        autocomplete.map((suggestion) => (
                          <li
                            key={suggestion._id}
                            onClick={() =>
                              handleRoute(
                                suggestion.type,
                                suggestion.product_name
                              )
                            }
                          >
                            {suggestion.product_name}
                            <span>in {suggestion.type}</span>
                          </li>
                        ))
                      ) : (
                        <p style={{ textAlign: "center" }}>
                          Oops, No Result Found
                        </p>
                      )}
                      <li
                        style={{
                          textAlign: "center",
                          color: "grey",
                          padding: 5,
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontSize: 12,
                        }}
                        onClick={() =>
                          handleRoute(
                            suggestion.category,
                            suggestion.product_name
                          )
                        }
                      >
                        view all results{" "}
                      </li>
                    </ul>
  
  </div> */}
  {/* <div className="col-1 align-self-center">
  <Box sx={{ minWidth: 120 }}>
      <FormControl fullWidth>
        <InputLabel id="demo-simple-select-label">Age</InputLabel>
        <Select
          labelId="demo-simple-select-label"
          id="demo-simple-select"
          value={category}
          label="Category"
          onChange={handleChange}
        >
          <MenuItem value={10}>Ten</MenuItem>
          <MenuItem value={20}>Twenty</MenuItem>
          <MenuItem value={30}>Thirty</MenuItem>
        </Select>
      </FormControl>
    </Box>
    
    </div> */}
    {/* <div className="col-1 align-self-center">
    <button
                        className="submit"
                        type="submit"
                        onClick={handleSearch}
                      >
                        <img
                          src="/assets/images/image/Icon material-search.png"
                          style={{ height: "22px", opacity: "0.9" }}
                          alt="bedsdivans"
                        />
                      </button>
    </div> */}
  
  {/* <Box >
      <FormControl >
        <InputLabel id="demo-simple-select-label">Age</InputLabel>
        <Select
          labelId="demo-simple-select-label"
          id="demo-simple-select"
          value={age}
          label="Age"
          onChange={handleChange}
        >
          <MenuItem value={10}>Ten</MenuItem>
          <MenuItem value={20}>Twenty</MenuItem>
          <MenuItem value={30}>Thirty</MenuItem>
        </Select>
      </FormControl>
    </Box> */}


              {/* <div className="col-md-6 align-self-center">
                <div className="header-actions search-section">
                  <div className="header_search-form">
                    <form className="action-form" action="#">
                      <input
                        className="form-control"
                        placeholder="Search"
                        type="text"
                        onChange={(e) => setQuery(e.target.value)}
                      /> */}
                      {/* <Box >
                      <FormControl >
                        <InputLabel id="demo-simple-select-label">Age</InputLabel>
                        <Select
                          labelId="demo-simple-select-label"
                          id="demo-simple-select"
                          value={age}
                          label="Age"
                          onChange={handleChange}
                        >
                          <MenuItem value={10}>Ten</MenuItem>
                          <MenuItem value={20}>Twenty</MenuItem>
                          <MenuItem value={30}>Thirty</MenuItem>
                        </Select>
                      </FormControl>
                    </Box> */}
                      {/* <button
                        className="submit"
                        type="submit"
                        onClick={handleSearch}
                      >
                        <img
                          src="/assets/images/image/Icon material-search.png"
                          style={{ height: "22px", opacity: "0.9" }}
                          alt="bedsdivans"
                        />
                      </button>
                    </form>
                    <ul
                      className="search_suggestions"
                      style={{ display: query ? "block" : "none" }}
                    >
                      {autocomplete.length ? (
                        autocomplete.map((suggestion) => (
                          <li
                            key={suggestion._id}
                            onClick={() =>
                              handleRoute(
                                suggestion.type,
                                suggestion.product_name
                              )
                            }
                          >
                            {suggestion.product_name}
                            <span>in {suggestion.type}</span>
                          </li>
                        ))
                      ) : (
                        <p style={{ textAlign: "center" }}>
                          Oops, No Result Found
                        </p>
                      )}
                      <li
                        style={{
                          textAlign: "center",
                          color: "grey",
                          padding: 5,
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontSize: 12,
                        }}
                        onClick={() =>
                          handleRoute(
                            suggestion.category,
                            suggestion.product_name
                          )
                        }
                      >
                        view all results{" "}
                      </li>
                    </ul>
                  </div>
                </div>
              </div> */}
              <div className="col-md-2 align-self-center">
                <div className="cartfordesktop">
                  <div className="header-actions">
                    <div className="header-bottom-set dropdown">
                      <ul>
                        <button className="">
                          <span
                            onClick={() => router.push("/cart")}
                            className="header-action-btn header-action-btn-cart offcanvas-toggle pr-0"
                            style={{ cursor: "pointer" }}
                          >
                            {/* <ShoppingCartIcon /> */}
                            <Image
                              width={25}
                              height={25}
                              src="/assets/images/icons/basket.webp"
                              alt=""
                            />
                            <span className="header-action-num">
                              {getCartCount()}
                            </span>
                          </span>
                        </button>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              <div className="col-md-1 align-self-center">
                <div className="whislist">
                  <Image
                    width={40}
                    height={40}
                    src="/assets/images/icons/heart.png"
                    alt=""
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="header-bottom d-lg-none sticky-nav bg-white">
          <div className="container position-relative">
            <div className="row align-self-center">
              <div className="col-auto align-self-center">
                <div className="header-logo">
                  <a href="#">
                    <Image
                      src="/assets/images/logo/logo.png"
                      width={128}
                      height={128}
                      alt="Site Logo"
                    />
                  </a>
                </div>
              </div>

              <div className="col align-self-center">
                <div className="header-actions">
                  <div className="header_account_list">
                    <a className="header-action-btn search-btn">
                      <i className="icon-magnifier"></i>
                    </a>
                    <div className="dropdown_search">
                      <form className="action-form" action="#">
                        <input
                          className="form-control"
                          placeholder="Enter your search key"
                          type="text"
                        />
                        <button className="submit" type="submit">
                          <i className="icon-magnifier"></i>
                        </button>
                      </form>
                    </div>
                  </div>

                  <div className="header-bottom-set dropdown">
                    <button
                      className="dropdown-toggle header-action-btn"
                      data-bs-toggle="dropdown"
                    >
                      <i className="icon-user"></i>
                    </button>
                    <ul>
                      <li>
                        <a className="dropdown-item" href="my-account.html">
                          My account
                        </a>
                      </li>
                      <li>
                        <a className="dropdown-item" href="checkout.html">
                          Checkout
                        </a>
                      </li>
                      <li>
                        <a className="dropdown-item" href="login.html">
                          Sign in
                        </a>
                      </li>
                    </ul>
                  </div>

                  <a
                    href="#offcanvas-cart"
                    className="header-action-btn header-action-btn-cart offcanvas-toggle pr-0"
                  >
                    <i className="icon-handbag"></i>
                    <span className="header-action-num">01</span>
                  </a>
                  <a
                    href="#offcanvas-mobile-menu"
                    className="header-action-btn header-action-btn-menu offcanvas-toggle d-lg-none"
                  >
                    <i className="icon-menu"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* For Mobile Menu Components start */}

        <div className="MenuforMobile">
          <Menu />
        </div>
        {/* For Mobile Menu Components start */}
        <div
          className="d-none d-lg-block sticky-nav"
          style={{ backgroundColor: "#204697" }}
        >
          <div
            className="container position-relative"
            style={{ maxWidth: "100%" }}
          >
            <div className="row">
              <div className="col-md-12 align-self-center">
                <div className="main-menu manu-color-white">
                  <ul>
                    {/* <li className="dropdown position-static"><a href="/DivanBed"> <b>Divan Beds</b> </a> */}
                    <li className="dropdown position-static ">
                      <Link className="ForBold" href="/product/divanbed">
                        Divan Beds
                      </Link>
                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0 " href="shop-left-sidebar.html">
                                <Image
                                  className="img-responsive w-100 "
                                  src="/assets/images/menu-icons/BedsDivan.png"
                                  width={258}
                                  height={238}
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>

                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by Type </b>
                              </a>
                            </li>
                            <li>
                              <Link href="/divanbed/linen-Fabric-Divan-Beds">
                                Linen Fabric Divan Beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/velvet-Fabric-Divan-Beds">
                                Velvet Fabric Divan Beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/velvet-Fabric-Divan-Beds">
                                Suede Fabric Divan Bed
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/suede-Fabric-Divan-Beds">
                                Low Divan Beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/leather-Divan-Beds">
                                Leather Divan Beds
                              </Link>
                            </li>
                            <li>
                              <a
                                href="shop-right-sidebar.html"
                                style={{ color: "#262884" }}
                              >
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by size </b>
                              </a>
                            </li>
                            <li>
                              <Link href="/divanbed/two-feet-bed">
                                Small Single (2'6ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/three-feet-bed">
                                Single (3ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/four-feet-bed">
                                Small Double (4ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/four-six-feet-bed">
                                Double (4'6ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/five-feet-bed">
                                King (5ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/six-feet-bed">
                                Super King (6ft)
                              </Link>
                            </li>
                          </ul>
                          <ul
                            className="d-block"
                            style={{ marginRight: "0px !important" }}
                          >
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Divan Beds Complete Set</b>
                              </a>
                            </li>
                            <li>
                            <Link href="/divanbed/linen-Fabric-Divan-Beds">
                                Linen Fabric Divan Beds
                              </Link>
                            </li>
                          </ul>
                        </li>
                        <li></li>
                      </ul>
                    </li>
                    <li className="dropdown position-static">
                      <Link className="ForBold" href="/product/allbeds">
                        All Beds
                      </Link>

                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  className="img-responsive w-100"
                                  src="/assets/images/menu-icons/submenu-divanbeds.png"
                                  width={258}
                                  height={238}
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Sleigh Beds </b>
                              </a>
                            </li>
                            <li>
                              <Link href="/allbed/floridabed">
                                Florida Bed Range
                              </Link>
                            </li>
                            <li>
                              <Link href="/allbed/ambassadorbed">
                                Ambassador Range
                              </Link>
                            </li>
                            <li>
                              <Link href="/allbed/kendall">Kendall Bed</Link>
                            </li>
                            <li>
                              <Link href="/allbed/manocobed">Manoco Range</Link>
                            </li>
                            <li>
                              <Link href="/allbed/royalbed">Royal Beds</Link>
                            </li>
                            <li>
                              <Link href="/allbed/swanbed">Swan Bed Range</Link>
                            </li>
                            <li>
                              <Link href="/allbed/wingbed">Wing Bed Range</Link>
                            </li>
                            <li>
                              <Link href="/allbed/winchester">
                                Winchester Bed
                              </Link>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title1">
                              <Link href="/allbed/ottoman-bed" style={{ color: "#262884" }}>
                                Ottoman Beds
                              </Link>
                            </li>
                            <li className="title1">
                              <Link href="/allbed/kids-bed" style={{ color: "#262884" }}>
                                Kids Beds
                              </Link>
                            </li>
                            <li className="title1">
                              <Link href="/allbed/leaher-bed" style={{ color: "#262884" }}>
                                Leather beds
                              </Link>
                            </li>
                            <li className="title1">
                              <Link href="/allbed/nevada-bed" style={{ color: "#262884" }}>
                                Nevada Beds
                              </Link>
                            </li>
                            <li className="title1">
                              <Link href="/allbed/storage-bed" style={{ color: "#262884" }}>
                                 Storage Bed 
                              </Link>
                            </li>
                          </ul>
                          <ul
                            className="d-block"
                            style={{ marginRight: "0px !important" }}
                          >
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Divan Beds </b>
                              </a>
                            </li>
                            <li>
                              <Link href="/divanbed/linen-Fabric-Divan-Beds">
                                Linen Fabric Divan Beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/velvet-Fabric-Divan-Beds">
                                Velvet Fabric Divan Beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/velvet-Fabric-Divan-Beds">
                                Suede Fabric Divan Bed
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/suede-Fabric-Divan-Beds">
                                Low Divan Beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/divanbed/leather-Divan-Beds">
                                Leather Divan Beds
                              </Link>
                            </li>
                            <li>
                              <a
                                href="shop-right-sidebar.html"
                                style={{ color: "#262884" }}
                              >
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li className="dropdown position-static">
                      <Link href="/product/headboard"> Headboard </Link>

                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  className="img-responsive w-100"
                                  src="/assets/images/menu-icons/submenu-headboard.png"
                                  width={258}
                                  height={238}
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Shop by Type</b>
                              </a>
                            </li>
                            <li>
                              <Link href="/headboard/PanerlHeadboard">
                                Panel Headboard
                              </Link>
                            </li>
                            <li>
                              <Link href="/headboard/cubeheadboard">
                                Diamond Cube Headboard
                              </Link>
                            </li>
                            <li>
                              <Link href="/headboard/plainheadboard">
                                Plain Headboard
                              </Link>
                            </li>
                            <li>
                              <a href="#" style={{ color: "#262884" }}>
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>

                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Shop by size</b>
                              </a>
                            </li>
                            <li>
                              <Link href="/headboard/two-feet-headboard">
                                Small Single (2'6ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/headboard/three-feet-headboard">
                                Single (3ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/headboard/four-feet-headboard">
                                Small Double (4ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/headboard/four-six-feet-headboard">
                                Double (4'6ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/headboard/five-feet-headboard">
                                King (5ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/headboard/six-feet-headboard">
                                Super King (6ft)
                              </Link>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li className="dropdown position-static">
                      <Link href="/product/Mattressess">Mattresses</Link>

                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  className="img-responsive w-100"
                                  src="/assets/images/menu-icons/submenu-matteress.png"
                                  width={258}
                                  height={238}
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by Type </b>
                              </a>
                            </li>
                            <li>
                              <Link href="/mattressess/orthopedicmattressess">
                                Orthopedic Mattresses
                              </Link>
                            </li>
                            <li>
                              <Link href="/mattressess/pocketmattressess">
                                Pocket Mattresses
                              </Link>
                            </li>
                            <li>
                              <Link href="/mattressess/memoryformmattressess">
                                Memory Form Mattresses
                              </Link>
                            </li>
                            <li>
                              <Link href="/mattressess/pillowtopmattressess">
                                Pillow Top Mattresses
                              </Link>
                            </li>
                            <li>
                              <a
                                href="shop-left-sidebar.html"
                                style={{ color: "#262884" }}
                              >
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Shop by size</b>
                              </a>
                            </li>
                            <li>
                              <Link href="/mattressess/two-feet-mattress">
                                Small Single (2'6ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/mattressess/three-feet-mattress">
                                Single (3ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/mattressess/four-feet-mattress">
                                Small Double (4ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/mattressess/four-six-feet-mattress">
                                Double (4'6ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/mattressess/five-feet-mattress">
                                King (5ft)
                              </Link>
                            </li>
                            <li>
                              <Link href="/mattressess/six-feet-mattress">
                                Super King (6ft)
                              </Link>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Shop by Comfort</b>
                              </a>
                            </li>
                            <li>
                              <a href="single-product.html">Very Firm</a>
                            </li>
                            <li>
                              <a href="single-product-variable.html">Firm</a>
                            </li>
                            <li>
                              <a href="single-product-affiliate.html">Medium</a>
                            </li>
                            <li>
                              <a href="single-product-group.html">Soft</a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>

                    <li className="dropdown position-static">
                      <Link className="ForBold" href="/product/sofa">
                        Sofa
                      </Link>
                      {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  width={258}
                                  height={238}
                                  className="img-responsive w-100"
                                  src="/assets/images/menu-icons/Sofa Banner.png"
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by Type </b>
                              </a>
                            </li>
                            <li>
                              <Link href="/sofa/chairbed">Chair beds</Link>
                            </li>
                            <li>
                              <Link href="/sofa/2seatersofa">
                                2 seater sofa beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/sofa/3seatersofa">
                                3 seater sofa beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/sofa/4seatersofa">
                                4 seater sofa beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/sofa/cornersofa">
                                Corner sofa beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/sofa/storagesofa">
                                Storage sofa beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/sofa/fabricsofa">
                                Fabric sofa beds
                              </Link>
                            </li>
                            <li>
                              <Link href="/sofa/chairs">Chairs</Link>
                            </li>
                            <li>
                              <Link href="/sofa/footstools">Footstools</Link>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <Link
                                href="/sofa/chairbed"
                                style={{ color: "#262884" }}
                              >
                                <b>Fabric Sofa</b>
                              </Link>
                            </li>
                            <li>
                              <Link href="/sofa/fabricsofa">
                                <a>Fabric Sofa</a>
                              </Link>
                            </li>
                            <li>
                              <Link href="/sofa/championsofa">
                                Champion Sofa
                              </Link>
                            </li>
                            <li>
                              <Link href="/sofa/chicagosofa">Chicago Sofa</Link>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title1">
                              <Link href="#" style={{ color: "#262884" }}>
                                <b>Leather beds</b>
                              </Link>
                            </li>
                            <li className="title1">
                              <Link href="#" style={{ color: "#262884" }}>
                                <b>Nevada Beds</b>
                              </Link>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Storage Bed</b>
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li className="dropdown position-static">
                      <Link href="/product/gardenfurniture">
                        Garden Furniture
                      </Link>
                      {/* <i
                                            className="ion-ios-arrow-down"></i> */}

                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  width={258}
                                  height={238}
                                  className="img-responsive w-100"
                                  src="/assets/images/menu-icons/submenu-garden-furniture.png"
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Shop by Type </b>
                              </a>
                            </li>
                            <li>
                              <Link href="/gardenfurniture/gardensofa">
                                Garden Sofa Sets
                              </Link>
                            </li>
                            <li>
                              <Link href="/gardenfurniture/gardendining">
                                Garden Dining Sets
                              </Link>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Fabric Sofa</b>
                              </a>
                            </li>
                            <li>
                              <a href="single-product.html">Champion Sofa</a>
                            </li>
                            <li>
                              <Link href="single-product-variable.html">
                                Chicago Sofa
                              </Link>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Leather beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Nevada Beds</b>
                              </a>
                            </li>
                            <li className="title1">
                              <a href="#" style={{ color: "#262884" }}>
                                <b>Storage Bed</b>
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>

                    {/* <li className="dropdown "><a href="#"> <b> Garden Furniture </b></a>
                                    <ul className="sub-menu">
                                        <li className="dropdown position-static"><a href="blog-grid-left-sidebar.html">Garden Sofa Sets
                                             </a> 
                                        </li>
                                        <li className="dropdown position-static"><a href="blog-list-left-sidebar.html">Garden Dining Sets
                                            </a>
                                        </li>
                                    </ul>
                                </li> */}

                    <li className="dropdown position-static">
                      <Link href="/product/livingroom">
                        Living Room Furniture
                      </Link>
                      {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  width={258}
                                  height={238}
                                  className="img-responsive w-100"
                                  src="/assets/images/menu-icons/Living Room Furniture.png"
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title1">
                              <Link
                                href="/livingroom/chestdrawers"
                                style={{ color: "#262884" }}
                              >
                                <a>Chest Drawers</a>
                              </Link>
                            </li>
                            <li className="title1">
                              <Link
                                href="/livingroom/shelf"
                                style={{ color: "#262884" }}
                              >
                                <a>Shelf</a>
                              </Link>
                            </li>
                            <li className="title1">
                              <Link
                                href="/livingroom/wardrobes"
                                style={{ color: "#262884" }}
                              >
                                <a>Wardrobes</a>
                              </Link>
                            </li>
                            <li className="title1">
                              <Link
                                href="/livingroom/shelf"
                                style={{ color: "#262884" }}
                              >
                                <b>Nevada Beds</b>
                              </Link>
                            </li>
                            <li className="title1">
                              <Link href="#" style={{ color: "#262884" }}>
                                <b>Storage Bed</b>
                              </Link>
                            </li>
                          </ul>

                          <ul className="d-block">
                            <li className="title">
                              <Link href="#" style={{ color: "#262884" }}>
                                <b>Chairs</b>
                              </Link>
                            </li>
                            <li>
                              <Link href="/livingroom/chairs">
                                <a>Chairs</a>
                              </Link>
                            </li>

                            <li>
                              <Link href="/livingroom/armchair">
                                <a>Arm Chairs</a>
                              </Link>
                            </li>
                            <li>
                              <Link href="/livingroom/rockingchairs">
                                Rocking Chairs
                              </Link>
                            </li>
                            <li>
                              <Link href="/livingroom/loungechairs">
                                Lounge Chairs
                              </Link>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>

                    <li className="dropdown position-static">
                      <Link href="/product/diningset"> Dining Set </Link>
                      {/* <i
                                            className="ion-ios-arrow-down"></i> */}
                      <ul className="mega-menu d-block">
                        <li className="d-flex">
                          <ul className="d-block">
                            <li>
                              <a className="p-0" href="shop-left-sidebar.html">
                                <Image
                                  width={258}
                                  height={238}
                                  className="img-responsive w-100"
                                  src="/assets/images/menu-icons/Dining Set.png"
                                  alt="BedsDivan"
                                />
                              </a>
                            </li>
                          </ul>
                          <ul className="d-block">
                            <li className="title">
                              <a href="#" style={{ color: "#262884" }}>
                                <b> Dining Table Set </b>
                              </a>
                            </li>
                            <li>
                              <Link href="/diningset/2seaterdiningset">
                                2 Seater Dining Sets
                              </Link>
                            </li>
                            <li>
                              <Link href="/diningset/4seaterdiningset">
                                4 Seater Dining Sets
                              </Link>
                            </li>
                            <li>
                              <Link href="/diningset/6seaterdiningset">
                                6 Seater Dining Sets
                              </Link>
                            </li>
                            <li>
                              <Link href="/diningset/8seaterdiningset">
                                8 Seater Dining Sets
                              </Link>
                            </li>
                            <li>
                              <a
                                href="shop-right-sidebar.html"
                                style={{ color: "#262884" }}
                              >
                                <b>View All</b>
                              </a>
                            </li>
                          </ul>

                          <ul className="d-block">
                            <li className="title1">
                              <Link
                                href="/diningset/diningchairs"
                                style={{ color: "#262884" }}
                              >
                                <b>Dining Chairs</b>
                              </Link>
                            </li>
                            <li className="title1">
                              <Link
                                href="/diningset/diningtables"
                                style={{ color: "#262884" }}
                              >
                                <b>Dining Tables</b>
                              </Link>
                            </li>
                            <li className="title1">
                              <Link
                                href="/diningset/sideboards"
                                style={{ color: "#262884" }}
                              >
                                <b>Sideboards</b>
                              </Link>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <a href="contact.html" style={{ color: "red" }}>
                        <b>Sale</b>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
