import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import Image from 'next/image';

export default function Review(){
    return(
        <div>
            <Head>
            <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
        <link href="/style/plugins/plugins.min.css/" rel="stylesheet"></link>
        <link href="/style/vendor/vendor.min.css/" rel="stylesheet"></link>
        <link rel="icon" href="/logo (1).png" />
            </Head>
<div className="container-fluid">
            <div className="row border mt-6 mb-10">
            <div className="col-md-3 CoustmerReviewMobile">
              <div className="review-card">
                <article className="review">
                  <aside className="review__consumer-information">
                    <div className="consumer-information">
                      <div className="consumer-information__picture">
                        {/* <Image width={128} height={128} alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" className="lazyloaded" data-ll-status="loaded" /> */}
                      </div>
                      <div className="consumer-information__details">
                        <div className="consumer-information__name">
                          Jodie Nash
                        </div>
                        <div className="consumer-information__data">
                          <div className="consumer-information__review-count">
                            <i
                              className="fa fa-pencil-square-o"
                              aria-hidden="true"
                            ></i>
                            <span>1 reviews</span>
                          </div>
                          <div className="consumer-information__location">
                            <i
                              className="fa fa-map-marker"
                              aria-hidden="true"
                            ></i>
                            <span>GB</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </aside>
                  <section className="review__content">
                    <div className="review-content__header" v-pre="">
                      <div className="review-content-header">
                        <div className="star-rating--medium">
                          {/* <Image width={128} height={128} src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" alt="5 stars: Excellent" className="lazyloaded" data-ll-status="loaded" /> */}
                        </div>
                        <div className="review-content-header__dates">
                          <span className="trigger">4 hours ago</span>
                        </div>
                      </div>
                    </div>
                    <div className="review-content__body">
                      <h2 className="review-content__title">
                        Excellent service excelle
                      </h2>
                      <p className="review-content__text">
                        Excellent service excellent bed...
                      </p>
                    </div>
                  </section>
                  <div className="review__actions">
                    <div className="review-actions">
                      <div className="review-actions__main">
                        <div className="review-action brand-find-useful">
                          <button className="button--subtle button--subtle-label-below">
                            <i
                              className="fa fa-thumbs-o-up"
                              aria-hidden="true"
                            ></i>
                            <span>Useful</span>
                          </button>
                        </div>

                        <div className="brand-share-button-wrapper">
                          <button className="button--subtle button--subtle-label-below">
                            <i
                              className="fa fa-share-alt"
                              aria-hidden="true"
                            ></i>
                            <span>Share</span>
                          </button>
                        </div>
                        <div className="review-action reply">
                          <button className="button--subtle button--subtle-label-below">
                            <i className="fa fa-reply" aria-hidden="true"></i>
                            <span>Reply</span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </article>
              </div>
            </div>
            <div className="col-md-3 CoustmerReviewMobile">
              <div className="review-card">
                <article className="review">
                  <aside className="review__consumer-information">
                    <div className="consumer-information">
                      <div className="consumer-information__picture">
                        {/* <Image width={128} height={128} alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" className="lazyloaded" data-ll-status="loaded" /><noscript><Image alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" /></noscript> */}
                      </div>
                      <div className="consumer-information__details">
                        <div className="consumer-information__name">
                          Mary Fletcher
                        </div>
                        <div className="consumer-information__data">
                          <div className="consumer-information__review-count">
                            <i
                              className="fa fa-pencil-square-o"
                              aria-hidden="true"
                            ></i>
                            <span>8 reviews</span>
                          </div>
                          <div className="consumer-information__location">
                            <i
                              className="fa fa-map-marker"
                              aria-hidden="true"
                            ></i>
                            <span>GB</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </aside>
                  <section className="review__content">
                    <div className="review-content__header" v-pre="">
                      <div className="review-content-header">
                        <div className="star-rating--medium">
                          {/* <Image width={128} height={128}  src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" alt="5 stars: Excellent" className="lazyloaded" data-ll-status="loaded" /> */}
                        </div>
                        <div className="review-content-header__dates">
                          <span className="trigger">7 hours ago</span>
                        </div>
                      </div>
                    </div>
                    <div className="review-content__body">
                      <h2 className="review-content__title">
                        Over the mood with
                      </h2>
                      <p className="review-content__text">
                        My order arrived when they said it would...
                      </p>
                    </div>
                  </section>
                  <div className="review__actions">
                    <div className="review-actions">
                      <div className="review-actions__main">
                        <div className="review-action brand-find-useful">
                          <button className="button--subtle button--subtle-label-below">
                            <i
                              className="fa fa-thumbs-o-up"
                              aria-hidden="true"
                            ></i>
                            <span>Useful</span>
                          </button>
                        </div>

                        <div className="brand-share-button-wrapper">
                          <button className="button--subtle button--subtle-label-below">
                            <i
                              className="fa fa-share-alt"
                              aria-hidden="true"
                            ></i>
                            <span>Share</span>
                          </button>
                        </div>
                        <div className="review-action reply">
                          <button className="button--subtle button--subtle-label-below">
                            <i className="fa fa-reply" aria-hidden="true"></i>
                            <span>Reply</span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </article>
              </div>
            </div>
            <div className="col-md-3 CoustmerReviewMobile">
              <div className="review-card">
                <article className="review">
                  <aside className="review__consumer-information">
                    <div className="consumer-information">
                      <div className="consumer-information__picture">
                        {/* <Image width={128} height={128} alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" className="lazyloaded" data-ll-status="loaded" /> */}
                      </div>
                      <div className="consumer-information__details">
                        <div className="consumer-information__name">
                          Emma Bridgman
                        </div>
                        <div className="consumer-information__data">
                          <div className="consumer-information__review-count">
                            <i
                              className="fa fa-pencil-square-o"
                              aria-hidden="true"
                            ></i>
                            <span>4 reviews</span>
                          </div>
                          <div className="consumer-information__location">
                            <i
                              className="fa fa-map-marker"
                              aria-hidden="true"
                            ></i>
                            <span>GB</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </aside>
                  <section className="review__content">
                    <div className="review-content__header" v-pre="">
                      <div className="review-content-header">
                        <div className="star-rating--medium">
                          {/* <Image width={128} height={128}  src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" alt="5 stars: Excellent" className="lazyloaded" data-ll-status="loaded" /> */}
                        </div>
                        <div className="review-content-header__dates">
                          <span className="trigger">9 hours ago</span>
                        </div>
                      </div>
                    </div>
                    <div className="review-content__body">
                      <h2 className="review-content__title">
                        Small double divan bed
                      </h2>
                      <p className="review-content__text">
                        Bed and headboard both lovely...
                      </p>
                    </div>
                  </section>
                  <div className="review__actions">
                    <div className="review-actions">
                      <div className="review-actions__main">
                        <div className="review-action brand-find-useful">
                          <button className="button--subtle button--subtle-label-below">
                            <i
                              className="fa fa-thumbs-o-up"
                              aria-hidden="true"
                            ></i>
                            <span>Useful</span>
                          </button>
                        </div>

                        <div className="brand-share-button-wrapper">
                          <button className="button--subtle button--subtle-label-below">
                            <i
                              className="fa fa-share-alt"
                              aria-hidden="true"
                            ></i>
                            <span>Share</span>
                          </button>
                        </div>
                        <div className="review-action reply">
                          <button className="button--subtle button--subtle-label-below">
                            <i className="fa fa-reply" aria-hidden="true"></i>
                            <span>Reply</span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </article>
              </div>
            </div>
            <div className="col-md-3 CoustmerReviewMobile">
              <div className="review-card">
                <article className="review">
                  <aside className="review__consumer-information">
                    <div className="consumer-information">
                      <div className="consumer-information__picture">
                        {/* <Image width={128} height={128} alt="BedsDivan" src="https://www.bedsdivans.co.uk/wp-content/uploads/2019/08/dummy-pic.png" className="lazyloaded" data-ll-status="loaded" /> */}
                      </div>
                      <div className="consumer-information__details">
                        <div className="consumer-information__name">
                          David whitham
                        </div>
                        <div className="consumer-information__data">
                          <div className="consumer-information__review-count">
                            <i
                              className="fa fa-pencil-square-o"
                              aria-hidden="true"
                            ></i>
                            <span>4 reviews</span>
                          </div>
                          <div className="consumer-information__location">
                            <i
                              className="fa fa-map-marker"
                              aria-hidden="true"
                            ></i>
                            <span>GB</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </aside>
                  <section className="review__content">
                    <div className="review-content__header" v-pre="">
                      <div className="review-content-header">
                        <div className="star-rating--medium">
                          {/* <Image width={128} height={128}  src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" alt="5 stars: Excellent" className="lazyloaded" data-ll-status="loaded" /> */}
                        </div>
                        <div className="review-content-header__dates">
                          <span className="trigger">7 hours ago</span>
                        </div>
                      </div>
                    </div>
                    <div className="review-content__body">
                      <h2 className="review-content__title">
                        Excellent service and fas
                      </h2>
                      <p className="review-content__text">
                        Excellent service and fast delivery...
                      </p>
                    </div>
                  </section>
                  <div className="review__actions">
                    <div className="review-actions">
                      <div className="review-actions__main">
                        <div className="review-action brand-find-useful">
                          <button className="button--subtle button--subtle-label-below">
                            <i
                              className="fa fa-thumbs-o-up"
                              aria-hidden="true"
                            ></i>
                            <span>Useful</span>
                          </button>
                        </div>

                        <div className="brand-share-button-wrapper">
                          <button className="button--subtle button--subtle-label-below">
                            <i
                              className="fa fa-share-alt"
                              aria-hidden="true"
                            ></i>
                            <span>Share</span>
                          </button>
                        </div>
                        <div className="review-action reply">
                          <button className="button--subtle button--subtle-label-below">
                            <i className="fa fa-reply" aria-hidden="true"></i>
                            <span>Reply</span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </article>
              </div>
            </div>
          </div>
          </div>
        </div>
    )
}