import Head from "next/head";
import Image from "next/image";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import Review from "../../components/Review";
import axios from "axios";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { css } from "@emotion/react";
import ClipLoader from "react-spinners/ClipLoader";

function Shop() {
  const router = useRouter();
  const [products, setProducts] = useState([]);
  const [page, setPage] = useState(1);
  const [serverpage, setServerPage] = useState();
  const [loading, setloading] = useState(false);
  const [category, setCategory] = useState("");
  const [headboardCategory, setHeadboardCategory] = useState("");
  const [mattressCategory, setMattressCategory] = useState("");
  const [gardernFurnitureCategory, setGardernFurnitureCategory] = useState("");
  const [sofaCategory, setSofaCategory] = useState("");
  const [livingRoomCategory, setLivingRoomCategory] = useState("");
  const [diningSetCategory, setDiningSetCategory] = useState("");
  const [maxPrice, setMaxPrice] = useState(1000);

  const [sort, setSort] = useState(0);

  console.log(products);

  useEffect(() => {
    setPage(1);
    setloading(true);
    setProducts([]);

    async function getProducts() {
      await axios
        .get(
          `/api/search?query=${router.query.search}&category=${category}&headboardCategory=${headboardCategory}&mattressCategory=${mattressCategory}&sort=${sort}&gardernFurnitureCategory=${gardernFurnitureCategory}&sofaCategory=${sofaCategory}&livingRoomCategory=${livingRoomCategory}&diningSetCategory=${diningSetCategory}&maxPrice=${maxPrice}`
        )
        .then((response) => {
          console.log(response);
          setProducts(response.data.data);
          setServerPage(parseInt(response.data.count));
          setPage(1);
          setloading(false);
        });
    }
    getProducts();
  }, [
    router.query.search,
    router.asPath,
    category,
    headboardCategory,
    mattressCategory,
    sort,
    gardernFurnitureCategory,
    sofaCategory,
    livingRoomCategory,
    diningSetCategory,
    maxPrice,
  ]);

  const loadNextPage = async () => {
    setloading(true);

    axios
      .get(
        `/api/search?query=${
          router.query.search
        }&category=${category}&headboardCategory=${headboardCategory}&mattressCategory=${mattressCategory}&sort=${sort}&page=${
          page + 1
        }&gardernFurnitureCategory=${gardernFurnitureCategory}&sofaCategory=${sofaCategory}&livingRoomCategory=${livingRoomCategory}&diningSetCategory=${diningSetCategory}&maxPrice=${maxPrice}`
      )
      .then((response) => {
        console.log(response);
        setProducts([...products, ...response.data.data]);
        setServerPage(response.data.count);
        setPage(page + 1);
        setloading(false);
      });
  };

  console.log(
    `/api/hello?query=${router.query.search}&category=${category}&headboardCategory=${headboardCategory}&mattressCategory=${mattressCategory}&sort=${sort}&page=${page}`
  );

  const override = css`
    display: block;
    margin: 0 auto;
    border-color: red;
  `;
  return (
    <div>
      <div>
        <Head>
          <title>BedsDivans</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          ></link>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          ></link>
          <link rel="icon" href="/logo (1).png" />
        </Head>
        <div>
          <Header />
          <div className="container mt-6">
            <div className="row">
              <div className="col-md-3">
                <h5>
                  {" "}
                  <b> PRODUCT CATEGORIES </b>
                </h5>

                <div
                  class="accordion md-accordion"
                  id="accordionEx"
                  role="tablist"
                  aria-multiselectable="true"
                >
                  <div class="mt-3 " role="tab" id="headingOne1">
                    <a
                      data-toggle="collapse"
                      data-parent="#accordionEx"
                      href="#collapseOne1"
                      aria-expanded="true"
                      aria-controls="collapseOne1"
                    >
                      <h6 class="mb-0" style={{ color: "#7c7c7c" }}>
                        <a
                          href=""
                          style={{ textDecoration: "none", color: "#7c7c7c" }}
                        >
                          {" "}
                          <b> Beds </b>
                        </a>
                        <span style={{ float: "right" }}>
                          {" "}
                          <i class="fa fa-angle-down" aria-hidden="true"></i>
                        </span>
                      </h6>
                    </a>
                  </div>
                  <div>
                    <label for="beds">Choose a DivanBeds:</label>

                    <select
                      name="headboard"
                      id="headboard"
                      className="divanbed-selector"
                      value={category}
                      onChange={(e) => setCategory(e.target.value)}
                    >
                      <option value="">Choose a Category</option>
                      <option value="Headboard">
                        Velvet Fabric Divan Beds
                      </option>
                      <option value="Headboard">
                        Velvet Fabric Divan Beds
                      </option>
                      <option value="Velvet Fabric Divan Beds">
                        Velvet Fabric Divan Beds
                      </option>
                      <option value="Linen Fabric DivanBed">
                        {" "}
                        Linen Fabric DivanBed
                      </option>
                      <option value="Suede Fabric Divan Beds">
                        Suede Fabric Divan Beds
                      </option>
                      <option value="Low Divan Beds">Low Divan Beds</option>
                      <option value=" Leather Divan Beds">
                        {" "}
                        Leather Divan Beds
                      </option>
                    </select>
                    <button
                      onClick={() => setCategory("")}
                      style={{
                        display: category ? "block" : "none",
                        color: "red !important",
                        cursor: "pointer",
                        textDecoration: "underline",
                      }}
                    >
                      Remove Bed Filter
                    </button>
                  </div>

                  <div class="mt-3" role="tab" id="headingTwo2">
                    <a
                      class="collapsed"
                      data-toggle="collapse"
                      data-parent="#accordionEx"
                      href="#collapseTwo2"
                      aria-expanded="false"
                      aria-controls="collapseTwo2"
                    >
                      <h6 class="mb-0">
                        <a
                          href=""
                          style={{ textDecoration: "none", color: "#7c7c7c" }}
                        >
                          {" "}
                          <b>Headboards</b>
                        </a>
                        <span style={{ float: "right" }}>
                          {" "}
                          <i class="fa fa-angle-down" aria-hidden="true"></i>
                        </span>
                      </h6>
                    </a>
                  </div>
                  {/* <div
                    id="collapseOne1"
                    class="collapse show"
                    role="tabpanel"
                    aria-labelledby="headingOne1"
                    data-parent="#accordionEx"
                  >
                    <div class="card-body">
                      <ul className="item-menu">
                        <li>
                          <button
                            onClick={() =>
                              setCategory("Panel Headboard")
                            }
                          >
                              Panel Headboard </button>
                        </li>
                        <li>
                          <button
                            onClick={() =>
                              setCategory("Cube Headboard")
                            }
                          >
                            Cube Headboard
                          </button>
                        </li>
                        <li>
                          <button
                            onClick={() =>
                              setCategory("Plain Headboard")
                            }
                          >
                            Plain Headboard
                          </button>
                        </li>
                        <li>
                          <button onClick={() => setCategory("Emerald Headboard")}>
                          Emerald Headboard
                          </button>
                        </li>
                        <li>
                          <button
                            onClick={() => setCategory("Supreme Headboard (8 vertical panels)")}
                          >
                          Supreme Headboard 
                          </button>
                        </li>
                        <li>
                          <button onClick={() => setCategory("")}>
                            Remove Filter
                          </button>
                        </li>
                      </ul>
                    </div>
                  </div> */}

                  <label for="headboard">Choose Headboard:</label>

                  <select
                    name="headboard"
                    id="headboard"
                    className="divanbed-selector"
                    value={headboardCategory}
                    onChange={(e) => setHeadboardCategory(e.target.value)}
                  >
                    <option value="">Select Headboard</option>
                    <option value="Panel Headboard">Panel Headboard</option>
                    <option value="Cube Headboard">Cube Headboard</option>
                    <option value="Plain Headboard">Plain Headboard</option>
                    <option value="Emerald Headboard">Emerald Headboard</option>
                  </select>

                  <button
                    onClick={() => setHeadboardCategory("")}
                    style={{
                      display: headboardCategory ? "block" : "none",
                      color: "red !important",
                      cursor: "pointer",
                      textDecoration: "underline",
                    }}
                  >
                    Remove Bed Filter
                  </button>

                  <div
                    id="collapseTwo2"
                    class="collapse"
                    role="tabpanel"
                    aria-labelledby="headingTwo2"
                    data-parent="#accordionEx"
                  >
                    <div class="card-body">
                      <label for="Headboard">Choose:</label>
                    </div>
                  </div>
                  <div className="mt-3">
                    <h6 class="mb-0">
                      <a
                        href=""
                        style={{ textDecoration: "none", color: "#7c7c7c" }}
                      >
                        {" "}
                        <b>Mattressess</b>
                      </a>{" "}
                    </h6>
                  </div>
                  <div>
                    <label for="headboard">Choose a Mattressess:</label>

                    <select
                      name="mattress"
                      id="mattress"
                      className="divanbed-selector"
                      value={mattressCategory}
                      onChange={(e) => setMattressCategory(e.target.value)}
                    >
                      <option value="">Select mattress</option>
                      <option value="Orthopedic Mattress">
                        Orthopedic Mattress
                      </option>
                      <option value="Pocket Mattress">Pocket Mattress</option>
                      <option value="Memory Form Mattress">
                        Memory Form Mattress
                      </option>
                      <option value="Pillow Top Mattress">
                        Pillow Top Mattress
                      </option>
                    </select>
                  </div>
                  <button
                    onClick={() => setMattressCategory("")}
                    style={{
                      display: mattressCategory ? "block" : "none",
                      color: "red !important",
                      cursor: "pointer",
                      textDecoration: "underline",
                    }}
                  >
                    Remove Mattress Filter
                  </button>

                  {/* <div
                    id="collapseThree3"
                    class="collapse"
                    role="tabpanel"
                    aria-labelledby="headingThree3"
                    data-parent="#accordionEx"
                  >
                    <div class="card-body">
                      <ul className="item-menu">
                        <li>
                          <a href="#">Chest Draws</a>
                        </li>
                        <li>
                          <a href="#">Garden Furniture</a>
                        </li>
                      </ul>
                    </div>
                  </div> */}
                  <div className="mt-3">
                    <h6 class="mb-0">
                      <a
                        href=""
                        style={{ textDecoration: "none", color: "#7c7c7c" }}
                      >
                        {" "}
                        <b>Sofa</b>
                      </a>{" "}
                    </h6>
                  </div>
                  <div>
                    <label for="Sofa Product">Choose a Sofa:</label>
                    <div>
                      <select
                        name="sofa"
                        id="sofa"
                        className="divanbed-selector"
                        value={sofaCategory}
                        onChange={(e) => setSofaCategory(e.target.value)}
                      >
                        <option value="sofa product">Sofa product</option>
                        <option value="Fabric Sofa">Fabric Sofa</option>
                        <option value="Leather Sofa">Leather Sofa</option>
                        <option value="Chair Sofa Beds">Chair Sofa Beds</option>
                        <option value="Corner Sofa">Corner Sofa</option>
                        <option value="Emerald Headboard">
                          Emerald Headboard
                        </option>
                      </select>
                    </div>
                    <button
                      onClick={() => setSofaCategory("")}
                      style={{
                        display: sofaCategory ? "block" : "none",
                        color: "red !important",
                        cursor: "pointer",
                        textDecoration: "underline",
                      }}
                    >
                      Remove Sofa Filter
                    </button>
                  </div>
                  <div className="mt-3">
                    <h6 class="mb-0">
                      <a
                        href=""
                        style={{ textDecoration: "none", color: "#7c7c7c" }}
                      >
                        {" "}
                        <b>Garden Furniture</b>
                      </a>{" "}
                    </h6>
                  </div>
                  <div>
                    <label for="gardenfurniture">
                      Choose a Garden Furniture:
                    </label>

                    <select
                      name="Graden Furniture"
                      id="Garden Furniture"
                      className="divanbed-selector"
                      value={gardernFurnitureCategory}
                      onChange={(e) =>
                        setGardernFurnitureCategory(e.target.value)
                      }
                    >
                      <option value="">Select Garden Furniture</option>
                      <option value="Teak color">Teak color</option>
                      <option value="Black Ash">Black Ash</option>
                    </select>
                  </div>
                  <button
                    onClick={() => setGardernFurnitureCategory("")}
                    style={{
                      display: gardernFurnitureCategory ? "block" : "none",
                      color: "red !important",
                      cursor: "pointer",
                      textDecoration: "underline",
                    }}
                  >
                    Remove Garden Furniture Filter
                  </button>
                  <div className="mt-3">
                    <h6 class="mb-0">
                      <a
                        href=""
                        style={{ textDecoration: "none", color: "#7c7c7c" }}
                      >
                        {" "}
                        <b>Living Room Furniture</b>
                      </a>{" "}
                    </h6>
                  </div>
                  <div>
                    <label for="living room"> Choose Living Room :</label>

                    <select
                      name="living room"
                      id="living room"
                      className="divanbed-selector"
                      value={livingRoomCategory}
                      onChange={(e) => setLivingRoomCategory(e.target.value)}
                    >
                      <option value="">Select Living Room </option>
                      <option value="Chairs">Chairs</option>
                      <option value="Tables">Tables</option>
                      <option value="Tub Chairs">Tub Chairs</option>
                      <option value="Arm Chairs">Arm Chairs</option>
                      <option value="Lounge Chairs">Lounge Chairs</option>
                      <option value="Rocking Chairs">Rocking Chairs</option>
                      <option value="Chest Drawers">Chest Drawers</option>
                      <option value="Shelf">Shelf</option>
                      <option value="Drawer">Drawer</option>
                    </select>
                  </div>
                  <button
                    onClick={() => setLivingRoomCategory("")}
                    style={{
                      display: livingRoomCategory ? "block" : "none",
                      color: "red !important",
                      cursor: "pointer",
                      textDecoration: "underline",
                    }}
                  >
                    Remove Living Room Filter
                  </button>
                  <div className="mt-3">
                    <h6 class="mb-0">
                      <a
                        href=""
                        style={{ textDecoration: "none", color: "#7c7c7c" }}
                      >
                        {" "}
                        <b>Dinning Set</b>
                      </a>{" "}
                    </h6>
                  </div>
                  <div>
                    <label for="dining set">Choose a Dining set:</label>

                    <select
                      name="headboard"
                      id="headboard"
                      className="divanbed-selector"
                      value={diningSetCategory}
                      onChange={(e) => setDiningSetCategory(e.target.value)}
                    >
                      <option value="">Choose Dinning set</option>
                      <option value="2 Seater Dining Set">
                        2 Seater Dining Set
                      </option>
                      <option value="4 Seater Dining Set">
                        4 Seater Dining Set
                      </option>
                      <option value="6 Seater Dining Set">
                        6 Seater Dining Set
                      </option>
                      <option value="8 Seater Dining Set">
                        8 Seater Dining Set
                      </option>
                      <option value="2 Seater Dining Set">
                        2 Seater Dining Set
                      </option>
                      <option value="Dining Table">Dining Table</option>
                      <option value="Dining Chairs">Dining Chairs</option>
                      <option value="SideBoard">SideBoard</option>
                      <option value="Emerald Headboard">
                        Emerald Headboard
                      </option>
                    </select>
                  </div>
                  <button
                    onClick={() => setDiningSetCategory("")}
                    style={{
                      display: diningSetCategory ? "block" : "none",
                      color: "red !important",
                      cursor: "pointer",
                      textDecoration: "underline",
                    }}
                  >
                    Remove Dining Set Filter
                  </button>
                  {/* <div className="mt-3" >
<h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Mattresses</b></a> </h6>

</div>
<div className="mt-3" >
<h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Nevada Beds</b></a> </h6>

</div>
<div className="mt-3" >
<h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Ottoman Beds</b></a> </h6>

</div>
<div className="mt-3" >
<h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Rattan Garden Furniture</b></a> </h6>

</div> */}
                  {/* <div class="mt-3" role="tab" id="headingThree4">
    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree4"
      aria-expanded="false" aria-controls="collapseThree3">
     <h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Shop by Bed Size</b></a>
     <span style={{float:"right"}}>   <i class="fa fa-angle-down" aria-hidden="true"></i></span>
      </h6>
    </a>
  </div>

  
  <div id="collapseThree4" class="collapse" role="tabpanel" aria-labelledby="headingThree4" data-parent="#accordionEx">
    <div class="card-body">
    <ul className="item-menu">
          <li><a  href="#">Double (4"6)</a></li>
          <li><a href="#">King (5"0)</a></li>
          <li><a href="#">Single (3"0)</a></li>
          <li><a href="#">Small Double (4"0)</a></li>
          <li><a href="#">Super King (6"0)</a></li>
      </ul>
    </div>
  </div> */}

                  {/* <div class="mt-3" role="tab" id="headingThree5">
    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree5"
      aria-expanded="false" aria-controls="collapseThree3">
     <h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Sleigh Beds</b></a>
     <span style={{float:"right"}}>   <i class="fa fa-angle-down" aria-hidden="true"></i></span>
      </h6>
    </a>
  </div>

  
  <div id="collapseThree5" class="collapse" role="tabpanel" aria-labelledby="headingThree5" data-parent="#accordionEx">
    <div class="card-body">
    <ul className="item-menu">
          <li><a  href="#">Ambassador Range</a></li>
          <li><a href="#">Chesterfield Bed</a></li>
          <li><a href="#">Florida Bed Range</a></li>
          <li><a href="#">Kendall Bed</a></li>
          <li><a href="#">Manoco Range</a></li>
          <li><a href="#">Royal Beds</a></li>
          <li><a href="#">Swan Bed Range</a></li>
          <li><a href="#">Winchester Bed</a></li>
          <li><a href="#">Wing Bed Range</a></li>
      </ul>
    </div>
  </div> */}

                  {/* <div class="mt-3" role="tab" id="headingThree6">
    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree6"
      aria-expanded="false" aria-controls="collapseThree3">
     <h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Sofas</b></a>
     <span style={{float:"right"}}>   <i class="fa fa-angle-down" aria-hidden="true"></i></span>
      </h6>
    </a>
  </div>

  
  <div id="collapseThree6" class="collapse" role="tabpanel" aria-labelledby="headingThree6" data-parent="#accordionEx">
    <div class="card-body">
    <ul className="item-menu">
          <li><a  href="#">2 Seater</a></li>
          <li><a href="#">3 Seater</a></li>
          
          <li><a href="#">Fabric Sofa</a></li>

          <li><a href="#">Leather Sofa</a></li>
          <li><a href="#">NORTHBANK SOFA</a></li>
          <li><a href="#">Sofa Beds</a></li>
         
      </ul>
    </div>
  </div> */}
                  {/* <div className="mt-3" >
<h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Storage Bed</b></a> </h6>

</div> */}
                  {/* <div class="mt-3" role="tab" id="headingThree7">
    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree7"
      aria-expanded="false" aria-controls="collapseThree3">
     <h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Tables</b></a>
     <span style={{float:"right"}}>   <i class="fa fa-angle-down" aria-hidden="true"></i></span>
      </h6>
    </a>
  </div>

  
  <div id="collapseThree7" class="collapse" role="tabpanel" aria-labelledby="headingThree7" data-parent="#accordionEx">
    <div class="card-body">
    <ul className="item-menu">
          <li><a  href="#">Bar Tables</a></li>
          <li><a href="#">Coffee Table</a></li>
          
          <li><a href="#">Dining Tables</a></li>

          <li><a href="#">Dressing Table</a></li>
          <li><a href="#">Manicure Tables</a></li>
          <li><a href="#">Side Tables</a></li>
         
      </ul>
    </div>
  </div> */}
                  {/* <div className="mt-3" >
<h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Tub Chairs</b></a> </h6>

</div>
<div class="mt-3" role="tab" id="headingThree8">
    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree8"
      aria-expanded="false" aria-controls="collapseThree3">
     <h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Wardrobes</b></a>
     <span style={{float:"right"}}>   <i class="fa fa-angle-down" aria-hidden="true"></i></span>
      </h6>
    </a>
  </div>

  
  <div id="collapseThree8" class="collapse" role="tabpanel" aria-labelledby="headingThree8" data-parent="#accordionEx">
    <div class="card-body">
    <ul className="item-menu">
          <li><a  href="#">Shelf</a></li>  
      </ul>
    </div>
  </div>
  <div className="mt-3" >
<h6 class="mb-0"><a href="" style={{textDecoration:"none" , color:"#7c7c7c"}}> <b>Wingback Chairs</b></a> </h6>

</div> */}
                  <hr className="mt-3 " />
                  <h5 className="mt-3">
                    {" "}
                    <b>Popularity </b>
                  </h5>
                  <div className="mt-3">
                    <h6 class="mb-0">
                      <select
                        name="headboard"
                        id="headboard"
                        className="divanbed-selector"
                        value={sort}
                        onChange={(e) => setSort(e.target.value)}
                      >
                        <option value={0}>Recommended</option>
                        <option value={1}>Price low to high</option>
                        <option value={-1}>Price high to low</option>
                      </select>
                    </h6>
                  </div>
                  <hr className="mt-3 " />
                  <h5 className="mt-3">
                    {" "}
                    <b>FILTER BY PRICE </b>
                  </h5>
                  <div class="slider-price d-flex align-items-center my-4 mt-3">
                    <span class="font-weight-normal small text-muted mr-2">
                      $0
                    </span>
                    <form class="multi-range-field w-100">
                      <input
                        type="range"
                        id="cowbell"
                        name="cowbell"
                        min="50"
                        max="1000"
                        step="1"
                        value={maxPrice}
                        onChange={(e) => setMaxPrice(e.target.value)}
                      />
                    </form>
                    <span class="font-weight-normal small text-muted ml-2">
                      ${maxPrice}
                    </span>
                  </div>
                </div>
              </div>
              <div className="col-md-9" style={{ marginleft: "-6px" }}>
                <div style={{ float: "right" }}>
                  <span>
                    Show:{" "}
                    <a style={{ marginRight: "10px" }} href="#">
                      All
                    </a>
                    <a
                      class="btn  dropdown-toggle"
                      href="#"
                      role="button"
                      id="dropdownMenuLink"
                      data-toggle="dropdown"
                      aria-haspopup="true"
                      aria-expanded="false"
                    >
                      Sort by popularity
                    </a>
                    <div
                      class="dropdown-menu"
                      aria-labelledby="dropdownMenuLink"
                    >
                      <a class="dropdown-item" href="#!">
                        Sort by average rating
                      </a>
                      <a class="dropdown-item" href="#!">
                        Sort by latest
                      </a>
                      <a class="dropdown-item" href="#!">
                        Sort by price: low to high
                      </a>
                      <a class="dropdown-item" href="#!">
                        Sort by price: high to low
                      </a>
                    </div>
                  </span>
                </div>
                <div
                  style={{ display: "flex", flexWrap: "wrap", width: "100%" }}
                >
                  <ClipLoader
                    color={"black"}
                    loading={loading}
                    css={override}
                    size={50}
                  />

                  {!products.length && !loading ? (
                    <h1>No Products Found</h1>
                  ) : (
                    products.map((item) => {
                      let imageUrl;

                      if (item.type == "bed") {
                        imageUrl = item.images[0].color1.base_url;
                        console.log("ok");
                      } else if (item.type == "headboard") {
                        imageUrl = item.images[0].url;
                      } else if (item.type == "mattress") {
                        imageUrl = item.images;
                      } else if (item.type == "diningSet") {
                        imageUrl = item.images[0];
                      } else if (item.type == "gardenFurniture") {
                        imageUrl = item.images[0].url;
                      } else if (item.type == "sofa") {
                        imageUrl = item.images[0].url;
                      }

                      return (
                        <div
                          className="row "
                          style={{ marginTop: "86px", marginLeft: "-30px" }}
                        >
                          <div
                            className="col-md-4"
                            style={{ position: "relative", left: "20px" }}
                          >
                            <div class="card" style={{ width: "19rem" }}>
                              <a href="" style={{ textDecoration: "none" }}>
                                <img
                                  class="card-img-top"
                                  src={imageUrl}
                                  alt="Card image cap"
                                />
                              </a>
                              <div
                                class="card-body cardTxt"
                                style={{ paddingleft: "18px" }}
                              >
                                <h6 class="card-title  card-hoverText">
                                  {" "}
                                  <b> {item.product_name}</b>
                                </h6>
                                <p class="card-text ">
                                  <img
                                    src="assets/images/banner/Group 429.png"
                                    alt=""
                                  />
                                </p>
                                <a href="#" style={{ textDecoration: "none" }}>
                                  <p
                                    className="card-text"
                                    style={{ fontSize: "19px" }}
                                  >
                                    {" "}
                                    <b> £{item.price} </b>
                                    <del style={{ color: "#7c7c7c" }}>
                                      £{parseInt(item.price) + 200}
                                    </del>{" "}
                                  </p>
                                </a>
                                {/* <a href="#" class="btn btn-primary">Go somewhere</a> */}
                              </div>
                            </div>
                          </div>
                        </div>
                      );
                    })
                  )}
                </div>

                <div
                  style={{
                    display: "flex",
                    justifyContent: "center",
                    width: "100%",
                  }}
                >
                  <button
                    onClick={loadNextPage}
                    style={{
                      display: page < serverpage ? "block" : "none",
                      padding: "10px 20px",
                      color: "white",
                      backgroundColor: "blue",
                      borderRadius: 10,
                      marginTop: 20,
                    }}
                  >
                    Load More Beds
                  </button>
                </div>
                {/* second row start */}

                {/* <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
    
  </div>
</div>
                                

                            </div> */}
              </div>
              {/* fifth row end */}

              {/* six row start */}
              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
    
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
    
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
     
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
  
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
   
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
     
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
    
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
  
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
     
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
    
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
  
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
   
  </div>
</div>
                                

                            </div>

                        </div>
              */}
              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
  
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
  
  </div>
</div>
                                

                            </div>

                        </div>
                                */}
              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
  
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
     
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
     
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
  
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>
                                

                            </div>

                        </div>
                        */}
              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
    
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
   
  </div>
</div>
                                

                            </div>

                        </div>
                     */}
              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
     
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
     
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
   
  </div>
</div>
                                

                            </div>

                        </div>
                         */}
              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
   
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
   
  </div>
</div>
                                

                            </div>

                        </div> */}

              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>
                                

                            </div>

                        </div>
                  */}
              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
   
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
    
  </div>
</div>
                                

                            </div>

                        </div>
                          */}
              {/* <div className="row " style={{marginTop:"46px" , marginLeft:"-30px"}} >
                            <div className="col-md-4">
                               
                            <div class="card" style={{width:"19em"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>


                            </div>
                            <div className="col-md-4" style={{position:"relative" , left:"10px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
 
  </div>
</div>

                            </div>
                            <div className="col-md-4"  style={{position:"relative" , left:"20px"}}>
                            <div class="card" style={{width:"19rem"}}>
                            <a href="" style={{textDecoration:"none"}}>
  <img class="card-img-top" src="https://aspirestore.co.uk/49062-home_default/olivier-fabric-ottoman-bed.jpg" alt="Card image cap" /></a>
  <div class="card-body cardTxt" style={{paddingleft:"18px"}}>
    <h6 class="card-title  card-hoverText"> <b> Olivier Fabric Ottoman Bed </b></h6>
    <p class="card-text "><img src="assets/images/banner/Group 429.png" alt="" /></p>
    <a href="#"  style={{textDecoration:"none"}}><p className="card-text" style={{fontSize:"19px"}}> <b> £400.00 </b><del style={{color:"#7c7c7c"}}>£749.00</del> </p></a>
  
  </div>
</div>
                                

                            </div>

                        </div> */}
              <div
                className="Heading-product  "
                style={{ marginTop: "56px", marginLeft: "-10px" }}
              >
                <h3 className="text-center">
                  {" "}
                  <b> Why buy divan beds from bedsdivans </b>
                </h3>
                <p className="mt-4">
                  At bedsdivans we strongly believe in what you see is what you
                  get so it is important all of our images are exactly the same
                  item you will receive. Unlike most companies we do not edit
                  our pictures, our gallery is authentic and has not been made
                  to look any different. We also know that you don’t just want
                  ‘cheap’ beds; you want them to be durable yet comfortable. You
                  might want or need your bed super-fast, too, which is why we
                  only offer fast delivery for every order made on our website.
                  We can assure you at bedsdivans you will receive the best
                  customer service and quality that you cannot beat.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Shop;
