import React ,{useState} from 'react';
import Head from 'next/head';
import Link from 'next/link';
import {useForm} from "react-hook-form";

function Contactform() {

    const { register, handleSubmit} =useForm('');

    const onSubmit = (data) => {
        alert (JSON.stringify(data));
    }


   
    return (
        <div>
            <Head>
                <title>BedsDivans</title>
                <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        ></link>
        
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
        <link href="/style/plugins/plugins.min.css/" rel="stylesheet"></link>
        <link href="/style/vendor/vendor.min.css/" rel="stylesheet"></link>
        <link rel="icon" href="/logo (1).png" />
            </Head>

            <div className="">
            <form onSubmit={handleSubmit(onSubmit)} >
                <div className="row contact-form2">
                    <h3>Billing Details</h3>
                <div className="  col-md-6">
          <label htmlFor="name">Name:</label>
          <input
          {...register('name')}
          name="tittle"
            id="name"
            type="text"
           required
          />
         
          </div>
          <div className="  col-md-6 ">
              <label htmlFor="lname">Last Name</label>
              <input
              {...register('lname')}
                id="lname"
                type="text" />
          </div> 
          <div className="col-md-6 mt-4">
              <label htmlFor="cname">Company Name (optional)</label>
              <input
              {...register('cname')}
                 type="text"
                 id="cname"  />

          </div>
          <div className="col-md-6 mt-4">
              <label htmlFor="country">Country / Region *</label>
              <p className="country-name">United Kingdom (UK)</p>

          </div>
          <div className="col-md-12 mt-4">
              <label htmlFor="streetaddf">Street address *</label>
              <input 
              {...register('streetaddf')}
                type="text" 
                name="" 
                id="streetaddf"  placeholder="House number and street name" /> 
          </div>
          <div className="col-md-12 mt-4">
          <input 
          {...register('streetadds')}
                type="text" 
                name="" 
                id="streetadds"   placeholder="Apartment,suite,unit,etc. (Optional) " />

          </div>
          <div className="col-md-6 mt-4">
              <label htmlFor="town">Town / City *</label>
              <input 
              {...register('town')}
                type="text" 
                name="" 
                id="town"  /> 
          </div>
          <div className="col-md-6 mt-4">
              <label htmlFor="country">County (optional)</label>
              <input 
              {...register('country')}
                type="text" 
                name="" 
                id="country"  /> 
          </div>
          <div className="col-md-6 mt-4">
              <label htmlFor="postcode">Postcode *</label>
              <input 
              {...register('postcode')}
                type="text" 
                name="" 
                id="postcode"  /> 
          </div>
          <div className="col-md-6 mt-4">
              <label htmlFor="phone">Phone *</label>
              <input 
              {...register('phone')}
                type="tel" 
                id="phone"  />

          </div>
          <div className="col-md-12 mt-4">
          <label htmlFor="email">Email:</label>
          <input
          {...register('email')}
            id="email"
            type="email"
           
          />

          </div>
          <div className="col-md-12 mt-4">
              <label htmlFor="textare">order notes(optional)</label>
              <textarea className="text-area"
              {...register('value_name')}
            id="message"
            type="text"
            rows="4"
           
          />

          </div>
          
</div>
          <button type="submit">Send</button>
        </form>

            </div>
            
        </div>
    )
}

export default Contactform
