import Head from "next/head";
import Image from "next/image/";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";
import Link from "next/link";
// import { Tab, Tabs } from "react-bootstrap";
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
// import Menu from '../.next/comps/Menu'
import Header from '../components/Header';
import Footer from '../components/Footer';
import Review from '../components/Review';
import axios from "axios";
import { useEffect } from "react";
import { useState } from "react";
import ProductBox from "../components/comps/ProductBox";
import { useRouter } from "next/router";
import HomeMattress from "../components/comps/HomeMattress";
import Headboardtab from "../components/homefeaturetab/Headboardtab";
// import Mobilemenu from "../components/comps/Mobilemenu";
import Homemenunew from "../components/comps/Homemenunew";
import Award from "../components/award";
import Gardenfurnituretab from "../components/homefeaturetab/Gardenfurnituretab";


export default function Home({response , response1 , response2 , response3}) {
  const router = useRouter();
  console.log(response);
  console.log(response1);
  console.log(response2);
  console.log(response3);
  var images = [];
  var imgSlides = () =>
    images.map((num) => ({
   
    }));
  return (
    <div>
      <Head>
        <title>BedsDivans</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        ></link>
        
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
        <link href="/style/plugins/plugins.min.css/" rel="stylesheet"></link>
        <link href="/style/vendor/vendor.min.css/" rel="stylesheet"></link>
        <link rel="icon" href="/logo (1).png" />
      </Head>
       

      <div className="fordesktopmeu">
            <Header />
          </div>

      <div className=" formobilemenu">
            <Homemenunew />
          </div>
     
    
      

      
      

      <div className="section hidden">
        <div className="hero-slider swiper-container slider-nav-style-1 slider-dot-style-1">
          <div className="swiper-wrapper">
            <div className="hero-slide-item slider-height swiper-slide d-flex">
              <div className="container mt-10 text-center">
                <h1
                  className="HeadingForM"
                  style={{ fontSize: "85px", color: "#ffffff", textShadow:"2px 2px 4px #909090e0" }}
                >
                  <strong>Divan Beds</strong>
                </h1>
                <p
                  className="NextH"
                  style={{ fontSize: "28px", color: "#ffffff",lineHeight:"1.1",opacity:"0.8" }}
                >
                  Save upto 60% with Divan Beds
                </p>
                <div>
                  <button
                    className="ShopMobile"
                    style={{
                      color: "#ffffff",
                      backgroundColor: "#f22222",
                      padding: "9px",
                      borderRadius: "42px",
                      paddingLeft: "40px",
                      paddingRight: "40px",
                      fontSize: "18px",
                      paddingTop: "12px",
                      paddingBottom: "12px",
                      fontWeight:"300",
                      letterSpacing:"0.5px",
                      marginTop:"37px"
                    }}
                  >
                    
                    <b>SHOP NOW</b>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div className="swiper-pagination swiper-pagination-white"></div>
          <div className="swiper-buttons">
            <div className="swiper-button-next"></div>
            <div className="swiper-button-prev"></div>
          </div>
        </div>
      </div>
{/* desktopview start */}
<div className="award-section-destop">
      <div className="banner-bottom-style">
      <div className="container">
        <div className="row">
          <div className="col-3">
            <div className="banner-bottom-ineerbox">
                    <ul>
                      <li><Image src="/assets/images/banner/Group 594.svg" width={60} height={60} /></li>
                      <li><h6>Quick Shipping</h6>
                      <span> <p> on orders over $100 </p></span></li>
                    </ul>
            </div>
          </div>
          <div className="col-3">
            <div className="banner-bottom-ineerbox">
                    <ul>
                      <li><Image src="/assets/images/banner/Group 593@2x.png" width={60} height={60} /></li>
                      <li><h6>Made in UK</h6>
                      <span> <p> Divan Beds and Mattressess </p></span></li>
                    </ul>
            </div>
          </div>
          <div className="col-3">
            <div className="banner-bottom-ineerbox">
                    <ul>
                      <li><Image src="/assets/images/banner/Group 592.svg" width={60} height={60} /></li>
                      <li><h6>Best Quality</h6>
                      <span> <p> Lolem ipsum quality </p></span></li>
                    </ul>
            </div>
          </div>
          <div className="col-3">
            <div className="banner-bottom-ineerbox">
                    <ul>
                      <li><Image src="/assets/images/banner/Group 591.svg" width={60} height={60} /></li>
                      <li><h6>Interest Free Credit</h6>
                      <span> <p> Interest Free Credit </p></span></li>
                    </ul>
            </div>
          </div>
        </div>

        </div>
      </div>
      </div>
      {/* desktopview end */}

      {/* Mobile Start */}
      <div className="award-section-mobile">
      <Award/>
      </div>
      {/* Mobile end */}
      <hr className="banner-icons" />


 



      <div className="section mt-6 pb-100px bg-brown">
        {/* <div className="container container-custom ForMobileWidth2">
          <div className="row">
            <div className="col-md-6 top-banner-img forMobileWidth">
              <Image
              priority={true}
                alt="BedsDivan"
                width={500}
                height={500}
                src="/assets/images/banner/mattress-website-add.png"
                style={{ backgroundSize: "cover" }}
              />
            </div>
            <div className="col-md-6 top-banner-content forMobileWidth">
              <div className="row ">
                <div className="col-md-6 ">
                  <h2 className="title-top-first">
                    UP TO <br />
                    <span>60% </span>
                    <br />
                    off
                  </h2>
                </div>
                <div className="col-md-6">
                  <h3 className="title-top">
                    
                    <strong>Mattress </strong> <br /> <strong>Set</strong>
                  </h3>
                </div>
              </div>
            </div>
          </div>
        </div> */}

        <div className="container second-section-home">
          <div className="row" style={{width:"83%", margin:"0 auto"}}>
            <div className="col-md-12 text-center" data-aos="fade-up">
              <div className="section-title mb-0">
                <h2 className="title colorfirst">BedsDivans.co.uk</h2>
              </div>
              <p className="sub-title mb-6" style={{ fontWeight: "600",letterSpacing:"0.2px" }}>
                
                We’re one of the UK’s leading manufacturers of
                <span style={{ color: "#262884" }}> cheap divan beds</span> ,
                offering a rich selection of products in a variety of styles. At
                BedsDivans, we are committed to improving comfort and sleep
                quality without compromising style. We believe shopping for a
                bed, mattress, or set of
                <span style={{ color: "#262884" }}> rattan furniture</span> for
                your garden should be an enjoyable experience all the way
                through.
              </p>
              <hr />
            </div>
          </div>
        </div>

        {/* Best Quality Section Comment start */}
        {/* <div className="container bg-white pt-50px pb-50px ">
          <div className="row">
            <div
              className="col-lg-4 col-12 mb-md-30px mb-lm-30px"
              data-aos="fade-up"
              data-aos-delay="200"
            >
              <div className="banner-1 border-img">
                <Image 
                  src="/assets/images/banner/PikPng.com_quality-png_2801970.png"
                  alt="BedsDivan"
                  width={148}
                  height={128}
                  className="overlapIcon"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title">
                      <b>BEST QUALITY</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>

            <div
              className="col-lg-4 col-12 mb-md-30px mb-lm-30px"
              data-aos="fade-up"
              data-aos-delay="400"
            >
              <div className="banner-1">
                <Image className="overlapIcon"
                  src="/assets/images/banner/Group 580.png"
                  alt="BedsDivan"
                  width={128}
                  height={128}
                  
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title">
                      <b>QUICK DELIVERY</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>

            <div
              className="col-lg-4 col-12"
              data-aos="fade-up"
              data-aos-delay="600"
            >
              <div className="banner-1">
                <Image className="overlapIcon" 
                  src="/assets/images/banner/Group 581.png"
                  width={128}
                  height={128}
                  style={{position:"relative",left:"-10px "}}
                 
                  alt="BedsDivan"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title">
                      <b> LIVE ORDER TRACKING</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> */}

        {/* Best Quality Section Comment End */}

        {/* What are you looking For Start Comment */}

        {/* <div className="container pt-50px pb-50px ">
          <div className="row">
            <div className="col-md-12 text-center" data-aos="fade-up">
              <div className="section-title mb-0">
                <h2 className="title colorsecond">What are you looking for?</h2>
              </div>
            </div>
          </div>
          <div className="row pt-50px pb-50px ">
            <div className="col-lg-3 col-6 mb-md-30px mb-lm-30px">
              <div className="bannerCat">
                <Image
                  src="/assets/images/banner/divanbeds.png"
                  width={228}
                  height={228}
                  alt="BedsDivan"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title heading-product">
                      <b>Divan Complete Sets</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>

            <div className="col-lg-3 col-6 mb-md-30px mb-lm-30px">
              <div className="bannerCat">
                <Image
                  width={228}
                  height={228}
                  src="/assets/images/banner/CAMDEN-46-PLUS-BED-MUSTARD-FABRIC-2020-03-200-203-083-scaled-1920x1674-min-1920x1124-min-768x450 (1).jpg"
                  alt="BedsDivan"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title heading-product2">
                      <b>Storage Ottoman beds</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>

            <div className="col-lg-3 col-6 mb-md-30px mb-lm-30px">
              <div className="bannerCat">
                <Image
                  width={228}
                  height={228}
                  src="/assets/images/banner/sleigh bed.png"
                  alt="BedsDivan"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title heading-product3">
                      <b>Sleigh Beds</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>

            <div className="col-lg-3 col-6 mb-md-30px mb-lm-30px">
              <div className="bannerCat">
                <Image
                  width={228}
                  height={228}
                  src="/assets/images/banner/divanbed.png"
                  alt="BedsDivan"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title heading-product4">
                      <b>Divan Beds Set</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="row">
            <div className="col-lg-3 col-6 mb-md-30px mb-lm-30px">
              <div className="bannerCat">
                <Image
                  width={228}
                  height={228}
                  src="/assets/images/banner/headboard.png"
                  alt="BedsDivan"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title heading-product6">
                      <b>Headboard Beds</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>

            <div className="col-lg-3 col-6 mb-md-30px mb-lm-30px">
              <div className="bannerCat">
                <Image
                  width={228}
                  height={201}
                  src="/assets/images/banner/Group 14.png"
                  alt="BedsDivan"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title heading-product5">
                      <b>Mattressess Beds</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>

            <div className="col-lg-3 col-6 mb-md-30px mb-lm-30px">
              <div className="bannerCat">
                <Image
                  width={228}
                  height={228}
                  src="/assets/images/banner/garden-furniture.png"
                  alt="BedsDivan"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title heading-product7">
                      <b>Garden Furniture </b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>

            <div className="col-lg-3 col-6 mb-md-30px mb-lm-30px">
              <div className="bannerCat">
                <Image
                  width={228}
                  height={228}
                  src="/assets/images/banner/Sofa.png"
                  alt="BedsDivan"
                />
                <div className="info justify-content-start">
                  <div className="content align-self-center">
                    <h5 className="title heading-product8">
                      <b>Sofa Beds</b>
                    </h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> */}

        {/* What are you looking For End Comment */}


        {/* <div className="text-center">
          <div className="">
            <a
              href="#"
              className="btn btn-primary ForMobileGap"
              style={{
                width: "223px",
                marginBottom: "23px",
                backgroundColor: "#262884",
              }}
            >
              VIEW ALL PRODUCT
            </a>
          </div>
        </div> */}
      </div>

     

      <div className="section product-tab-area bg-brown mt-6">
        <div className="feature-background pb-100px" style={{ marginTop: "-81px" }}>
          <div className="container-fluid  RecomdFor">
            <div className="row">
              <div className="col-md-12 text-center" data-aos="fade-up">
                <div className="section-title mb-0">
                  <h2 className="title mt-6 colorRed">Featured Products</h2>
                  {/* <p className="">
                    We’re one of the UK’s leading manufacturers of cheap divan
                    beds, offering a rich selection of <br />
                    products in a variety of styles.
                  </p> */}
                </div>
              </div>

               
            </div>
            {/* New tabs start */}
            <Tabs>
        <div className="container pt-2 pb-6"> 
          <div className="row tab-inner-sofa-row">
          <TabList>
      <Tab><div className="tab-inner-sofa"><Image src="/assets/images/banner/Group 611.png" width={50} height={50} /><p>Divan bed</p></div></Tab>
      <Tab><div className="tab-inner-sofa"> <Image src="/assets/images/banner/Group 686.svg" width={50} height={50} /><p>Mattress</p></div></Tab>
      <Tab><div className="tab-inner-sofa"><Image src="/assets/images/banner/Group 688.svg" width={50} height={50} /><p>Headboard</p></div></Tab>
      <Tab><div className="tab-inner-sofa"><Image src="/assets/images/banner/Group 687.svg" width={50} height={50} /><p>Garden Furniture</p></div></Tab>
    </TabList>
          </div>
        </div>
   

    <TabPanel>
    <div className="row">
    {response.map((item) => {
                  console.log(item);
                  return (
                    <ProductBox
                      src={item.images[0].color1.base_url}
                      title={item.product_name}
                      price={item.price}
                    />
                  );
                })}
                       
                      </div>
    </TabPanel>
    <TabPanel>
     <HomeMattress response = {response3}/>
    </TabPanel>
    <TabPanel>
      <Headboardtab response = {response1} />
    </TabPanel>
    <TabPanel>
      <Gardenfurnituretab response = {response2} />
    </TabPanel>

  </Tabs>
            {/* New tabs end */}
            
          </div>
        </div>
      </div>

      <div className="section pt-6 pb-6">
        <div className="container-fluid">
          <div className="row ">
            <div className="col-md-12 text-center" data-aos="fade-up">
              <div className="section-title">
                <h2 className="title" style={{color:"#1E196C"}}>Shop by Bed Size</h2>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="size-box home-page-icon"  style={{marginBottom:"-14px",position:"relative",bottom:"12px"}}>
              <div className="single-box shop-by-size">
                <a href="#">
                  
                  <Image
                    width={128}
                    height={128}
                    alt="BedsDivan"
                    src="/assets/images/image/bed-sizes-01.png"
                  />
                </a>

                <p className="text-center mt-2" style={{color:"#00B2BD"}}>2.6ft Small Single</p>
              </div>

              <div className="single-box shop-by-size">
                <a href="#">
                  
                  <Image
                    width={128}
                    height={128}
                    alt="BedsDivan"
                    src="/assets/images/image/bed-sizes-02.png"
                  />
                </a>
                <p className="text-center mt-2" style={{color:"#00B2BD"}}>3ft Single</p>
              </div>

              <div className="single-box shop-by-size">
                <a href="#">
                  <Image
                    width={128}
                    height={128}
                    alt="BedsDivan"
                    src="/assets/images/image/bed-sizes-03.png"
                  />
                </a>
                <p className="text-center mt-2" style={{color:"#00B2BD"}}>4ft Small Double</p>
              </div>

              <div className="single-box shop-by-size">
                <a href="#">
                  <Image
                    width={128}
                    height={128}
                    alt="BedsDivan"
                    src="/assets/images/image/bed-sizes-04.png"
                  />
                </a>
                <p className="text-center  mt-2" style={{color:"#00B2BD"}}>4.6ft Double</p>
              </div>

              <div className="single-box shop-by-size">
                <a href="#">
                  <Image
                    width={128}
                    height={128}
                    alt="BedsDivan"
                    src="/assets/images/image/bed-sizes-05.png"
                  />
                </a>
                <p className="text-center mt-2" style={{color:"#00B2BD"}}>5ft King</p>
              </div>
              <div className="single-box shop-by-size">
                <a href="#">
                  <Image
                    width={128}
                    height={128}
                    alt="BedsDivan"
                    src="/assets/images/image/bed-sizes-N-01.png"
                  />
                </a>
                <p className="text-center mt-2" style={{color:"#00B2BD"}}>6ft Super King</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="section pt-6  bg-lightgray">
        <div className="container-fluid">
          <div className="row">
            <div className="col-md-12 text-center" data-aos="fade-up">
              <div className="section-title">
                <h2 className="title colorsecond">
                  
                   New Best Selling Bed
                </h2>
                <p className="sub-title mb-6" style={{ fontWeight: "600" }}>
                
                We’re one of the UK’s leading manufacturers of cheap divan
                    beds, offering a rich selection of 
                    products in a variety of styles.
              </p>
               
              </div>
            </div>
          </div>

          <div className="forSlider ForDesktopView" style={{paddingTop:"82px"}}>
        <div className="container-fluid">
          <div className="row " style={{ marginBottom: "20px" }}></div>
        </div>
        <Slider
          dots={true}
          slidesToShow={4}
          slidesToScroll={4}
          autoplay={false}
          arrows={true}
          autoplaySpeed={3000}
        >
          {imgSlides()}
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
                {/* <Image width={128} height={128} className="hover-image" src="/assets/images/product-image/2.jpg" alt="Product" /> */}
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <Image src="/assets/images/icons/heart1.png" width={20} height={20} />
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
              {/* <Image width={128} height={128} src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" width="120px" alt="" /> */}
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
                {/* <Image width={128} height={128} className="hover-image" src="/assets/images/product-image/2.jpg" alt="Product" /> */}
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <Image src="/assets/images/icons/heart1.png" width={20} height={20} />
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
              {/* <Image width={128} height={128} src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" width="120px" alt="" /> */}
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
                {/* <Image width={378} height={128}  className="hover-image" src="/assets/images/product-image/2.jpg" alt="Product" /> */}
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <Image src="/assets/images/icons/heart1.png" width={20} height={20} />
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
              {/* <Image width={128} height={128} src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" width="120px" alt="" /> */}
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
                {/* <Image  className="hover-image" src="/assets/images/product-image/2.jpg" alt="Product" /> */}
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <Image src="/assets/images/icons/heart1.png" width={20} height={20} />
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
              {/* <Image width={128} height={128} src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" width="120px" alt="" /> */}
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
                {/* <Image width={128} height={128} className="hover-image" src="/assets/images/product-image/2.jpg" alt="Product" /> */}
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <Image src="/assets/images/icons/heart1.png" width={20} height={20} />
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
              {/* <Image width={128} height={128} src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" width="120px" alt="" /> */}
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
        </Slider>
       
      </div>

          {/* For Mobile Strat */}

          <div className="forSlider ForMobileView pb-6">
            <div className="container-fluid">
              <div
                className="row "
                style={{ marginBottom: "20px", marginTop: "60px" }}
              ></div>
            </div>
            <Slider
              dots={true}
              slidesToShow={2}
              slidesToScroll={2}
              autoplay={false}
              arrows={true}
              autoplaySpeed={3000}
            >
              {imgSlides()}
              <div className="product productNew sliderProduct">
                <div className="thumb">
                  <a href="shop-left-sidebar.html" className="image">
                    <Image
                      width={128}
                      height={128}
                      src="/assets/images/banner/Homepage-banner.png"
                      className="rounded"
                      alt="Product"
                    />
                   
                  </a>

                  <div className="actions">
                    <a
                      href="wishlist.html"
                      className="action wishlist"
                      title="Wishlist"
                    >
                     <Image src="/assets/images/icons/heart.png" width={20} height={20} />
                    </a>
                  </div>
                </div>
                <div className="best-seller mb-6 mt-8 text-center">
                  <button>BUY NOW</button>
                </div>

                <div className="rating-product">
                  {/* <Image width={128} height={128} src="" width="120px" alt="BedsDivan"/> */}
                </div>
                <div className="contentNew">
                  <p>
                    Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                    DELIVERY
                  </p>
                  <span className="price"></span>
                </div>
              </div>
              <div className="product productNew sliderProduct">
                <div className="thumb">
                  <a href="shop-left-sidebar.html" className="image">
                    <Image
                      width={128}
                      height={128}
                      src="/assets/images/banner/Homepage-banner.png"
                      className="rounded"
                      alt="Product"
                    />
                    
                  </a>

                  <div className="actions">
                    <a
                      href="wishlist.html"
                      className="action wishlist"
                      title="Wishlist"
                    >
                      <Image src="/assets/images/icons/heart.png" width={20} height={20} />
                    </a>
                  </div>
                </div>
                <div className="best-seller mb-6 mt-8 text-center">
                  <button>BUY NOW</button>
                </div>

                <div className="rating-product">
                  {/* <Image width={128} height={128} src="" width="120px" alt="BedsDivan" /> */}
                </div>
                <div className="contentNew">
                  <p>
                    Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                    DELIVERY
                  </p>
                  <span className="price"></span>
                </div>
              </div>
              <div className="product productNew sliderProduct">
                <div className="thumb">
                  <a href="shop-left-sidebar.html" className="image">
                    <Image
                      width={128}
                      height={128}
                      src="/assets/images/banner/Homepage-banner.png"
                      className="rounded"
                      alt="Product"
                    />
                   
                  </a>

                  <div className="actions">
                    <a
                      href="wishlist.html"
                      className="action wishlist"
                      title="Wishlist"
                    >
                      <i className="icon-heart"></i>
                    </a>
                  </div>
                </div>
                <div className="best-seller mb-6 mt-8 text-center">
                  <button>BUY NOW</button>
                </div>

                <div className="rating-product">
                  {/* <Image width={128} height={128} src="" width="120px" alt="BedsDivan" /> */}
                </div>
                <div className="contentNew">
                  <p>
                    Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                    DELIVERY
                  </p>
                  <span className="price"></span>
                </div>
              </div>
              <div className="product productNew sliderProduct">
                <div className="thumb">
                  <a href="shop-left-sidebar.html" className="image">
                    <Image
                      width={128}
                      height={128}
                      src="/assets/images/banner/Homepage-banner.png"
                      className="rounded"
                      alt="Product"
                    />
                   
                  </a>

                  <div className="actions">
                    <a
                      href="wishlist.html"
                      className="action wishlist"
                      title="Wishlist"
                    >
                     <Image src="/assets/images/icons/heart.png" width={20} height={20} />
                    </a>
                  </div>
                </div>
                <div className="best-seller mb-6 mt-8 text-center">
                  <button>BUY NOW</button>
                </div>

                <div className="rating-product">
                  {/* <Image width={128} height={128} src="" width="120px" alt="BedsDivan" /> */}
                </div>
                <div className="contentNew">
                  <p>
                    Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                    DELIVERY
                  </p>
                  <span className="price"></span>
                </div>
              </div>
              <div className="product productNew sliderProduct">
                <div className="thumb">
                  <a href="shop-left-sidebar.html" className="image">
                    <Image
                      width={128}
                      height={128}
                      src="/assets/images/banner/Homepage-banner.png"
                      className="rounded"
                      alt="Product"
                    />
                   
                  </a>

                  <div className="actions">
                    <a
                      href="wishlist.html"
                      className="action wishlist"
                      title="Wishlist"
                    >
                     <Image src="/assets/images/icons/heart.png" width={20} height={20} />
                    </a>
                  </div>
                </div>
                <div className="best-seller mb-6 mt-8 text-center">
                  <button>BUY NOW</button>
                </div>

                <div className="rating-product">
                  {/* <Image width={128} height={128} src="https://cdn.trustpilot.net/brand-assets/4.1.0/stars/stars-5.svg" width="120px" alt="" /> */}
                </div>
                <div className="contentNew">
                  <p>
                    Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                    DELIVERY
                  </p>
                  <span className="price"></span>
                </div>
              </div>
            </Slider>
          </div>
          {/* For Mobile ENd */}
        </div>
        
       
       
        <div className="text-center">
                  <button
                    className="ShopMobile"
                    style={{
                      color: "#ffffff",
                      backgroundColor: "rgb(38, 40, 132)",
                      borderRadius: "6px",
                      fontSize: "15px",
                      padding: "12px 20px",
                      fontWeight:"400",
                      letterSpacing:"0.5px",
                      marginTop:"50px",
                      marginBottom:"37px",
                    }}
                  >
                    
                    <b>VIEW ALL PRODUCT</b>
                  </button>
                </div>
      </div>

      <div className="section pb-50px pt-50px bg-green moreOffer">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <div className="row align-items-center">
                <div className="col-lg-6 col-md-6 col-sm-12 text-center text-md-left">
                  <h2>Want to get 60% off? Save the time and money?</h2>
                </div>
                <div className="col-lg-6  col-md-6 col-sm-12 text-center">
                  <button className="more">More Offer</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="section pb-100px pt-100px explore-mattress" >
        <div className="container">
          <div className="row">
            <div className="col-md-12 text-center" data-aos="fade-up">
              <div className="section-title">
                <h2 className="title colorsecond">Explore Our Mattresses Set</h2>
                <p className="">
                  We’re one of the UK’s leading manufacturers of cheap divan
                  beds, offering a rich selection of <br />
                  products in a variety of styles.
                </p>
              </div>
            </div>
          </div>
          <div className="container">
          <div className="row">
            <div className="col-12 mattres-sectionb">
            <Image className="mattress-bannerone" src="/assets/images/mattressbanner/Group 693@2x.png"  width={1600} height={400} />
            </div>

          </div>
        <div className="row mt-4">
            <div className="col-6 col-xs-12">
            <Image src="/assets/images/mattressbanner/Group 696@2x.png" width={700} height={700} />
            </div>
            <div className="col-6 col-xs-12">
            <Image src="/assets/images/mattressbanner/Group 694@2x.png" width={600} height={280} />
            <div className="mt-4">
            <Image src="/assets/images/mattressbanner/Group 695@2x.png" width={600} height={290} />
            </div>
            </div>
            </div>
          
          </div>
          
          

          {/* <div className="row">
            <div className="col-md-4 text-center" data-aos="fade-up">
              <div className="sofa-product">
                <Image
                  width={300}
                  height={178}
                  alt="BedsDivan"
                  src="/assets/images/ProductImage/Mattress-03 (1).png"
                />
                <div className="text-block">
                <p>Pillow Top 1500 Pocket Medium firm Mattress Free UK Delivery</p>
                <div className="price">
                  <span className="colorRed">£899.99</span>
                </div>
                </div>
              </div>

              <div className="sofa-product ForMobileView22">
                <Image
                  width={300}
                  height={178}
                  alt="BedsDivan"
                  src="/assets/images/ProductImage/Mattress-02.png"
                />
               <div className="text-block">
               <p>1500 Pocket Tinsel Medium Firmness Mattress Free UK Delivery</p>
                <div className="price">
                  <span className="colorRed">£899.99</span>
                </div>
               </div>
              </div>
            </div>

            <div className="col-md-4 text-center" data-aos="fade-up" style={{overflow:"hidden"}}>
              <div className="product product-center productfor">
                <div className="thumb thumbfor">
                  <a href="shop-left-sidebar.html" className="image imagefor">
                    <Image
                      width={400}
                      height={128}
                      src="/assets/images/ProductImage/divan-bed-gtry-l.jpg"
                      alt="Product"
                    />
                  </a>
                  <span className="badges">
                    <span className="new">New</span>
                  </span>

                  <div className="content-center">
                    <p>
                      <i>
                        Chaise Lounge <br />
                        Blue Velvet
                      </i>
                    </p>
                    <span className="colorRed bold">£249.00</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="col-md-4 text-center" data-aos="fade-up">
              <div className="sofa-product ForMobileView22">
                <Image
                  width={300}
                  height={178}
                  alt="BedsDivan"
                  src="/assets/images/ProductImage/Mattress-03.png"
                />
                <div className="text-block">
                <p>Orthopedic Foam and Spring Mattress Medium Firmness</p>
                <div className="price">
                  <span className="colorRed">£899.99</span>
                </div>
                </div>
              </div>
              <div className="sofa-product">
                <Image
                  width={300}
                  height={178}
                  alt="BedsDivan"
                  src="/assets/images/ProductImage/Mattress-01.png"
                />
                <div className="text-block"><p>Dual Spring Memory Foam Mattress</p>
                <div className="price">
                  <span className="colorRed">£899.99</span>
                </div></div>
              </div>
            </div>
          </div> */}
        </div>
        <div className="text-center responsive-button">
                  <button
                    className="ShopMobile"
                    style={{
                      color: "#ffffff",
                      backgroundColor: "rgb(38, 40, 132)",
                      borderRadius: "6px",
                      fontSize: "15px",
                      padding: "12px 20px",
                      fontWeight:"400",
                      letterSpacing:"0.5px",
                      marginTop:"37px",
                      
                    }}
                  >
                    
                    <b>VIEW ALL PRODUCT</b>
                  </button>
                </div>
      </div>

      {/* <div className="section pb-100px pt-100px ">
        <div className="container">
          <div className="row">
            <div className="col-md-12" data-aos="fade-up">
              <div className="section-title text-center mb-11 ">
                <h2 className="title colorsecond ">Explore Our Mattresses</h2>
              </div>
            </div>
          </div>
        </div>
      </div> */}

      {/* <div className="forSlider ForDesktopView">
        <div className="container-fluid">
          <div className="row " style={{ marginBottom: "20px" }}></div>
        </div>
        <Slider
          dots={true}
          slidesToShow={4}
          slidesToScroll={4}
          autoplay={false}
          arrows={true}
          autoplaySpeed={3000}
        >
          {imgSlides()}
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
                
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <i className="icon-heart"></i>
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
             
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
                
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <i className="icon-heart"></i>
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
              
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
                
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <i className="icon-heart"></i>
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
              
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
                
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <i className="icon-heart"></i>
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
              
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
          <div className="product productNew sliderProduct">
            <div className="thumb">
              <a href="shop-left-sidebar.html" className="image">
                <Image
                  width={378}
                  height={128}
                  src="/assets/images/banner/Homepage-banner.png"
                  className="rounded"
                  alt="Product"
                />
               
              </a>

              <div className="actions">
                <a
                  href="wishlist.html"
                  className="action wishlist"
                  title="Wishlist"
                >
                  <i className="icon-heart"></i>
                </a>
              </div>
            </div>
            <div className="best-seller mb-6 mt-8 text-center">
              <button>BUY NOW</button>
            </div>

            <div className="rating-product">
              
            </div>
            <div className="contentNew">
              <p>
                Grey Linen Divan Base Or Set + Headboard & Mattress FREE UK
                DELIVERY
              </p>
              <span className="price"></span>
            </div>
          </div>
        </Slider>
        <div className="text-center mt-4">
          <div className="">
            <a
              href="#"
              className="btn btn-primary ForMobileGap"
              style={{
                width: "223px",
                marginBottom: "23px",
                backgroundColor: "#262884",
              }}
            >
              VIEW ALL PRODUCT
            </a>
          </div>
        </div>
      </div> */}
      
      {/* For Mobile end */}

      <div className="section pb-100px pt-100px bg-brown">
        <div className="container-fluid coustmer-review">
          <div className="row">
            <div className="col-md-12" data-aos="fade-up">
              <div className="section-title text-center mb-11">
                <h2 className="title colorsecond">
                  DISCOVER THE BENEFITS OF SHOPPING ONLINE AT BEDSDIVANS
                </h2>
                <p>
                  When looking for a new bed why not try the new designed divan
                  bed. It is affordable and looks great. At bedsdivans we spent
                  years in improving our wide selection of beds and we can
                  assure you will love our latest selection of divan beds. At
                  Bedsdivans we aim to work around your needs whether it comes
                  to short notice delivery dates or the slightest adjustment to
                  your bed we are always here to help you get the bed right for
                  you.
                </p>
              </div>
            </div>
          </div>

          <div className="text-center">
            <div className="">
              <a
                href="#"
                className="btn btn-primary"
                style={{ borderRadius: "36px", marginBottom: "23px" }}
              >
                More Services
              </a>
            </div>
          </div>

          <Review/>
        </div>
      </div>
<Footer/>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { req } = context;
  const size = req?.__NEXT_INIT_QUERY?.size;
  let sizes = "";

  size ? (sizes = size) : (sizes = "2FT 6");
  const data = await axios.post(
    "https://staggingx.bedsdivans.co.uk/api/products/getbeds",
    {
      method: "size",
      value: sizes,
    }
  );
  const data1 = await axios.get(
    "https://staggingx.bedsdivans.co.uk/api/headboard",
    {
      method: "size",
      value: sizes,
    }
  );
  const data2 = await axios.get(
    "https://staggingx.bedsdivans.co.uk/api/gardenfurniture", 
    {
      method: "size",
      value: sizes,
    }
  );
  const data3 = await axios.get(
    "https://staggingx.bedsdivans.co.uk/api/mattress",
    {
      method: "size",
      value: sizes,
    }
  );


  const response = data.data.data;
  const response1 = data1.data.data;

  const response2 = data2.data.data;
  
  const response3 = data3.data.data;
  
  return {
    props: { response , response1 , response2 , response3 }, // will be passed to the page component as props
  };
  
}




